### ISSUE TITLE
An Error Occurred When Loading the Javascript File 

### ISSUE THREAD

**Issue by 9ae8sdf76** [Jopyth/MMM-Remote-Control#100]
Hi, I'm really new to both MagicMirror and this module. I followed the instructions in the readme, and after restarting MM, I get the following error when accessing `http://<my ip>/remote.html`:

> If you see this message, an errror occured when loading the javascript file. Please go to the following link and see if this a known problem with your browser: Github issue page

I am at a loss for where to find appropriate log files, or what to do to correct the issue. The MM itself is running just fine.

**Comment by Jopyth** [comment]
I think you would need to check your internal browser console.

**Comment by HallofFrame** [comment]
Hey, this just happened to me too... I had everything working fine - remote control was great, interface was great.  I did a git pull and npm install to update, and now i only see this same message, regardless of what device/browser i'm using.
I also tried deleting module folder and re-installing from the curl command.  Still getting this message.
Any help getting remote control back is appreciated!

**Comment by HallofFrame** [comment]
Disparaging note to self:  "Hey HallofFrame, did you happen to try the very first thing that everyone, everywhere always tries whenever technology doesn't work right?" "Hit it, then restart?" "Yup, so how'd that go?" "Ya, it's working again, sorry"
