### ISSUE TITLE
MMM-Remote-Control cannot use

### ISSUE THREAD

**Issue by wadelijie** [Jopyth/MMM-Remote-Control#112]
Cannot read property 'split' of undefined
![image](https://user-images.githubusercontent.com/8101986/51973534-d5240200-24b8-11e9-92f7-b36ae8c75313.png)

**Comment by Jopyth** [comment]
Are you sure this is related to Remote-Control-Module? Please check your `config.js` again and check if you installed this module and other modules correctly.
