### ISSUE TITLE
Hide modules with audio (like youtube videos or so)

### ISSUE THREAD

**Issue by RafaelCota** [Jopyth/MMM-Remote-Control#113]
Hi,
I'm using a video module (MMM-EmbedYoutube) for displaying a news channel, and when I HIDE it with MMM-Remote-Control, it only hides the images, but the audio stills on.

Same thing happened with MONITORON/MONITOROFF notification, but I managed to change the node_helper.js and get it to mute/unmute at the same time as it turned ON/OFF the monitor.

Is there a way to do it with HIDE?

Thank you in advanced,

**Comment by Jopyth** [comment]
I guess you need to change the MMM-EmbedYoutube module in question. You could implement the [suspend](https://github.com/MichMich/MagicMirror/tree/master/modules#suspend) and `resume` functions in that module to pause the video/stream?
