### ISSUE TITLE
Restart MagicMirror not working in version 2

### ISSUE THREAD

**Issue by rts58** [Jopyth/MMM-Remote-Control#118]
Hi,

Love the features of the new version.  However, when I attempt to restart mm via the web menu I get the following error:
```
 Whoops! There was an uncaught exception...
0|mm  | { Error: Cannot find module 'pm2'
0|mm  |     at Module._resolveFilename (module.js:543:15)
0|mm  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm  |     at Function.Module._load (module.js:473:25)
0|mm  |     at Module.require (module.js:586:17)
0|mm  |     at require (internal/module.js:11:18)
0|mm  |     at Class.controlPm2 (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:867:23)
0|mm  |     at Class.executeQuery (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:654:22)
0|mm  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:1009:26)
0|mm  |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|mm  |     at emitTwo (events.js:126:13) code: 'MODULE_NOT_FOUND' }
```
This worked in the previous version.  I'm on the develop branch of mm. Other menu items seem to work fine, have not tried them all.

**Comment by Madseason41** [comment]
same here

**Comment by JTD420** [comment]
Where do you see these errors? @rts58 

I also have issues with the newest Remote Control. 
I've managed to fix or find work-arounds for majority of the ones I've come across so far but ideally would like to know I've not made any mistakes myself!

This is a problem I _think_ I also have however I do not see/do not know where to find the error log! I simply am unable to press the Restart Magic Mirror 2 button.

Other power options work like shutdown/restart, refresh browser etc but not restarting MM.
To do that I have to login via SSH and issue `pm2 restart Magic Mirror;` manually!

**Comment by rts58** [comment]
I can see these errors by logging in via SSH and running: `pm2 logs mm`.  They are written to `~/.pm2/logs/mm-error.log`.

**Comment by ronanversendaal** [comment]
@rts58  I had the same problem. I was able to fix it by running `npm link pm2`.

After which I got another unrelated issue. My pm2 script has a different name and unless you supply a `pm2ProcessName` value in the config, it will automatically try to use the default 'mm' as script name.

**Comment by rts58** [comment]
@ronanversendaal I ran `npm link pm2` in the MMM-Remote-Control directory.  I got a warning:
```
npm WARN prefer global pm2@3.2.7 should be installed with -g
/home/pi/MagicMirror/modules/MMM-Remote-Control/node_modules/pm2 -> /usr/lib/node_modules/pm2
```
I gave it a try and I did see a `PM2 process: restart mm` in the mm-out.log, however mm did not restart, it just quit.  Should I have executed the command in a different directory e.g. node_modules?

**Comment by ronanversendaal** [comment]
I have submitted an PR: https://github.com/Jopyth/MMM-Remote-Control/pull/126 here fixing that issue. The script currently calls the stop method instead of restart.

**Comment by costascontis** [comment]
i have the same issue,i did a  "npm link pm2" in the MMM-Remote-Control directory and got: `/home/pi/MagicMirror/modules/MMM-Remote-Control/node_modules/pm2 -> /usr/lib/node_modules/pm2` .Now when i am trying to restart its just stop.Anyone knows when it will be fixed?

**Comment by ezar** [comment]
Same here!

**Comment by rts58** [comment]
@ronanversendaal fixed this with his pull request linked above.  I manually made his changes to the node_helper.js file and restart is now working correctly.  It can be closed once @Jopyth merges the pull request.

**Comment by maqlhr** [comment]
I have installed remote control last week and still restart is not working. it quits the magic mirror.
I did git pull in cd ~/MagicMirror/modules/MMM-Remote-Control directory but it says its up to date.

How can i fetch the above mentioned updated file node_helper.js which is fixed by @ronanversendaal

**Comment by rts58** [comment]
Since Jopyth has not merged the pull request, I don't think you can fetch the needed file.  I think you have to edit it manually like I did.  You can see the changes [here](https://github.com/Jopyth/MMM-Remote-Control/pull/126/files).

**Comment by maqlhr** [comment]
> @ronanversendaal fixed this with his pull request linked above. I manually made his changes to the node_helper.js file and restart is now working correctly. It can be closed once @Jopyth merges the pull request.

can you provide your changed file ? and how can we install it. just do npm install in the directory after replacing the changed file ?

**Comment by ezeholz** [comment]
I'm gonna close this issue now, if anyone is having the same problem double and triple check the following:
1. Check if PM2 is installed in your system. You should do `npm -g i pm2` in a terminal.
2. Link the PM2 into the MagicMirror instalation. Make sure your terminal is inside `/MagicMirror` folder and type `npm link pm2`
3. Make sure to have MagicMirror (2.12+) and Remote Control (2.1+) updated to the last version available.

If you still having problems, open a new issue.
Cheers ;D
