### ISSUE TITLE
removeDefaultValues() doesn't remove arrays and objects

### ISSUE THREAD

**Issue by aschulz90** [Jopyth/MMM-Remote-Control#12]
removeDefaultValues() doesn't properly remove all default values, like arrays and objects.

For example compliments gets saved like this, even though the compliments object is defined like this in the defaults:

```
{
	module: "compliments",
	position: "lower_third",
	config: {
		compliments: {
			morning: [
				"Good morning, handsome!",
				"Enjoy your day!",
				"How was your sleep?"
			],
			afternoon: [
				"Hello, beauty!",
				"You look sexy!",
				"Looking good today!"
			],
			evening: [
				"Wow, you look hot!",
				"You look nice!",
				"Hi, sexy!"
			]
		}
	}
}
```

The problem is, that `{} === {}` or `[] === []` equals false and therefore isn't being removed.

**Comment by Jopyth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [removeDefaultValues() doesn't remove arrays and objects](https://trello.com/c/q3AQyFGz/20-removedefaultvalues-doesn-t-remove-arrays-and-objects)

**Comment by Jopyth** [comment]
Thank you for pointing this out. Put it on my ToDo list.
