### ISSUE TITLE
Cannot access REST api.

### ISSUE THREAD

**Issue by Madseason41** [Jopyth/MMM-Remote-Control#120]
Upgraded to v2.
Config file is:
```
port: 9411   
 config: {
        // customCommand: {},  // Optional, See "Using Custom Commands" below
        // customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
        showModuleApiMenu: true, // Optional, Enable the Module Controls menu
        apiKey: "",         // Optional, See API/README.md for details
    }
```

I can access and use web ui just fine.

From home directory I run:
`
curl -X GET http://localhost:9411/api/monitor/off`

Output:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/monitor/off</pre>
</body>
</html>

```
Is there something I need to do to enable the API?

I have installed/ updated manually and via the script with no failures.

**Comment by ezar** [comment]
Same here!

**Comment by pyrosmiley** [comment]
Bumping this one. Thought it was a DNS issue of some kind (it's _always_ DNS) but nope, even locally any request simply comes back with a "`cannot GET`" error. This is from cURL, postman, and simply typing it into chrome. Let me know if there are logs or something I can get you.

**Comment by cschwarz007** [comment]
Same here - not working with error "`cannot GET`"

```
	port: 8081,
	address: "192.168.101.79",
	{
		module: 'MMM-Remote-Control',
		disabled: false,			
	},
```

**Comment by egomes951** [comment]
Hi,

Same problem. Can't use API.

**Comment by lawrence-jeff** [comment]
Same issue, duplicated in https://github.com/Jopyth/MMM-Remote-Control/issues/127

**Comment by mlcampbe** [comment]
Same problem here.

**Comment by Madseason41** [comment]
Someone try:

sudo npm i -g npm

and see if that fixes it. Else I did something I am unaware of and the api started working.

**Comment by mlcampbe** [comment]
That does not help me. I ran this:

sudo npm i -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.9.0
added 2 packages from 2 contributors, removed 2 packages and updated 10 packages in 73.451s

Still get the same "Cannot GET /api/module..." message

**Comment by ezar** [comment]
Same problem!

**Comment by Madseason41** [comment]
Then I have no clue why it started working. The only thing I did to the mirror was run the above mentioned command and then performed a reboot.

After that I opened a browser and went to http://lcoal.ip:port/api/test and got a success response. I tried hiding modules after that and it worked.

**Comment by stsergo** [comment]
If you have issue like this, just remove any unused modules or extra files from {{./MagicMirror/modules/}}

**Comment by Maleya** [comment]
bumping this as well. I updated to v2 and now have the same problem as everyone here. Even locally from the home folder.

**Comment by Tim0815** [comment]
Hi all,
this seems still to be an issue. The module is working perfectly well except this RESTfulish API functionality.
Please advise on how to proceed.
Thanks already!

**Comment by ezeholz** [comment]
Maybe you should try the command above mentioned `sudo npm i -g npm`
I suspect this is happening because the port number is changed, did you change it to another not being 8080?

**Comment by Tim0815** [comment]
Unfortunately, that didn't solve the issue. "/api/" is still not exposed. However, I'm able to send commands via "/remote?[...]"
It worked once with an earlier version of MagicMirror.

**Comment by ezeholz** [comment]
I don't know if this is a bug or something. How have you installed the MagicMirror? Did you try reinstalling everything? Maybe it's not a problem with this module itself. But I'll probably need more data on this to be able to solve it.

**Comment by Tim0815** [comment]
Are there any debugging capabilities?

**Comment by ezeholz** [comment]
Doesn't seem to. Shame. Try installing [my fork](https://github.com/ezeholz/MMM-Remote-Control), maybe the problem is solve in that one. I should probably add a more verbose output in the future.

**Comment by Tim0815** [comment]
I GOT IT!!! Finally.
With a bit of debugging and inserting a lot of `console.log` statements. ;-)
To all, who might have the same issue: Make sure, you do not have any more files or folders in "MagicMirror\modules\" folder, than actually necessary!!!
Cheers, Tim.

**Comment by Dresch360** [comment]
Is there a fix for this?
