### ISSUE TITLE
Config Error!

### ISSUE THREAD

**Issue by Roxx-R** [Jopyth/MMM-Remote-Control#123]
hi...
i am just a newbie, could do simple modules for now..
mm doesnt start normally in my case..
something wrong with the config..

1) i did a quick install, it was successfully installed..
2) moved file _"custom_menu.example.json"_ from _"/home/pi/MagicMirror/modules/MMM-Remote-Control"_   to  _"/home/pi/MagicMirror/config"_
3) added to my _config.js:_
  `		    {`
`        module: 'MMM-Remote-Control'`
`                     // uncomment the following line to show the URL of the remote control on the mirror`
`           position: 'bottom_right',`
`		     // you can hide this module afterwards from the remote control itself`
`        config: {`
`            apiKey: ''`
`        }`
`    },`

and made changes for IP address:
`var config = {`
`	address: "0.0.0.0",`
`	port: 8080,`
`	//ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],`
`	ipWhitelist: [] // Set [] to allow all IP addresses`

am i missing out thing? when MM is started, it says create a config file, without adding those lines in config, mm works.. moreover i dont understand about editing file _"custom_menu.example.json"_ .. its all confusing for me.. 
thanks!

**Comment by JTD420** [comment]
I'm having same issue... If I remove the module part from config.js it works but then I cannot access the mirror remote so I don't know what to do! Adding the module part in just results in the config error :(

(Removing the below gets rid of the config error.)
`{
module: 'MMM-Remote-Control'
// uncomment the following line to show the URL of the remote control on the mirror
position: 'bottom_right',
// you can hide this module afterwards from the remote control itself
config: {
apiKey: ''
}
},`

Then going to http://192.168.0.19:8080/remote.html results in
`This device is not allowed to access your mirror. 
Please check your config.js or config.js.sample to change this.`

**Comment by JTD420** [comment]
Hey I just fixed the problem @Roxx-R !

We were missing a `,` (comma) from the code right after the module!
It seems to be pasted like that a lot so I don't know how more people didn't have the same issue lol! 

So from what you pasted this would be the working fix

`{
module: 'MMM-Remote-Control',
// uncomment the following line to show the URL of the remote control on the mirror
position: 'bottom_right',
// you can hide this module afterwards from the remote control itself
config: {
apiKey: ''
}
},`

**Comment by Roxx-R** [comment]
good!
i tried again and the config.js loaded, i guess i have some error with this:
`var config = {`
`address: "0.0.0.0",`
`port: 8080,`
`//ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],`
`ipWhitelist: [] // Set [] to allow all IP addresses`

could you share me your config? i mean part of above lines? ip address.. how you have done?
make `ipwhitelist:` to `[]` to allow all ip addresses, then your device will be allowed i guess...

**Comment by JTD420** [comment]
Yes I couldn't figure out what was wrong with my IP either as I definitely whitelisted the correct IPs so I just changed it to `[]`

Hope that helps :)

**Comment by Roxx-R** [comment]
> good!
> i tried again and the config.js loaded, i guess then i must be having some error with this:
> `var config = {`
> `address: "0.0.0.0",`
> `port: 8080,`
> `//ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],`
> `ipWhitelist: [] // Set [] to allow all IP addresses`
> 
> could you share me your config? i mean part of above lines? ip address.. how you have done?
> make `ipwhitelist:` to `[]` to allow all ip addresses, then your device will be allowed i guess...

the config problem is solved! i typed `Whitelist:` instead of `ipWhitelist:` now MM starts..
**but still i am not able to access the remote interface on http://xx.xx.xxx.xxx:8080/remote.html, it says it took too long to respond, err_connection_timed_out**
i use [this website](https://www.iplocation.net/find-ip-address) to know my ip address..

anybody else having same problem?

**Comment by JTD420** [comment]
> > good!
> > i tried again and the config.js loaded, i guess then i must be having some error with this:
> > `var config = {`
> > `address: "0.0.0.0",`
> > `port: 8080,`
> > `//ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],`
> > `ipWhitelist: [] // Set [] to allow all IP addresses`
> > could you share me your config? i mean part of above lines? ip address.. how you have done?
> > make `ipwhitelist:` to `[]` to allow all ip addresses, then your device will be allowed i guess...
> 
> the config problem is solved! i typed `Whitelist:` instead of `ipWhitelist:` now MM starts..
> **but still i am not able to access the remote interface on http://xx.xx.xxx.xxx:8080/remote.html, it says it took too long to respond, err_connection_timed_out**
> i use [this website](https://www.iplocation.net/find-ip-address) to know my ip address..
> 
> anybody else having same problem?

Did you try removing the IPs from your whitelist and leaving `[]` in it's place?

I believe what you have done by renaming `ipWhitelist` to just `Whitelist` is essentially remove the mention of it from the code. 

So the rest of the modules (such as mmm-remote-control) are trying to access `ipWhitelist` which does not exist in your config file!

`// Set [] to allow all IP addresses` 
That is what you should try I think.

Let me know if that fixes things! @Roxx-R

**Comment by sergge1** [comment]
hi!
Just installed MagicMirror v.2.7.1. Works fine.
Now I am trying to install MMM-Remote-Control (further "RC").
What has been done:
1. Installed RC using command `bash -c "$(curl -s https://raw.githubusercontent.com/Jopyth/MMM-Remote-Control/master/installer.sh)"`
Here is the installation LOG
> Installation for the MagicMirror2 Remote-Control module started!
> 
> Notice: This script [//text was cut for simplicity] software.
> 
> >>> Continue? [y/N]? y
> 
> MagicMirror2 detected in: /home/pi/MagicMirror
> 
> >>> Is this correct and do you want to start installation? [y/N]? y
> 
> You can use either the master or the develop branch.
> The develop branch contains more features, but is also more likely to cause errors or crashes.
> This can be changed later by executing this script again, or using the git branch command.
> 
> By default the master branch will be installed.
> 
> >>> Do you want to install the develop branch instead? [y/N]? y
> 
> Cloning the repository on develop branch...
> 
> Cloning into 'MMM-Remote-Control'...
> remote: Enumerating objects: 926, done.
> remote: Total 926 (delta 0), reused 0 (delta 0), pack-reused 926
> Receiving objects: 100% (926/926), 785.89 KiB | 524.00 KiB/s, done.
> Resolving deltas: 100% (594/594), done.
> 
> Installing dependencies...
> 
> npm notice created a lockfile as package-lock.json. You should commit this file.
> added 25 packages from 22 contributors and audited 34 packages in 10.208s
> found 0 vulnerabilities
> 
> Done.
> 
> Installation finished.
> bash: line 147: /usr/local/bin/node: No such file or directory
> 
> >>> Do you want to view instructions on how to configure the module? [Y/n]? n
> 
> You should also set an API key in your config section!
>   It's dangerous to go alone! Take this. 
>   apiKey: ''
>   I made it just for you.
> 
> Have fun with the module, if you have any problems, please search for help on github or in the forum:
> 
>    Github : https://github.com/Jopyth/MMM-Remote-Control
>    Forum  : http://forum.magicmirror.builders
> 
> Do not forget to restart your MagicMirror2 to activate the module! Installation finished.

2. Updated the config.js in /home/pi/MagicMirror/config by the following code (without IPs configuration, just to check whether MM will start correctly.


```
modules: [
{
	module: 'MMM-Remote-Control'
	// uncomment the following line to show the URL of the remote control on the mirror
	position: "bottom_right"
	// you can hide this module afterwards from the remote control itself
	config: {
		//customCommand: {},  // Optional, See "Using Custom Commands" below
		//customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
		//showModuleApiMenu: true, // Optional, Enable the Module Controls menu
		apiKey: ""        // Optional, See API/README.md for details
		}
},
]
```

3. MM returns with the following error:

> pi@raspberrypi:~/MagicMirror $ DISPLAY=:0 npm start
> 
> > magicmirror@2.7.1 start /home/pi/MagicMirror
> > sh run-start.sh
> 
> Starting MagicMirror: v2.7.1
> Loading config ...
> WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:32
>  			position: "bottom_right"
>  			^^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at new Script (vm.js:74:7)
>     at createScript (vm.js:246:10)
>     at Object.runInThisContext (vm.js:298:10)
>     at Module._compile (internal/modules/cjs/loader.js:678:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
>     at Module.require (internal/modules/cjs/loader.js:658:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
> Loading module helpers ...
> Initializing new module helper ...
> Module helper loaded: updatenotification
> No helper found for module: helloworld.
> All module helpers loaded.
> Starting server on port 8080 ... 
> Server started ...
> Connecting socket for: updatenotification
> Sockets connected & modules started ...
> Launching application.

Could you help me with it - is it due to the new version of MM 2.7.1 or something else?

**Comment by sergge1** [comment]
@Roxx-R @JTD420 
issue above solved by putting COMMA after the module name and position name. Here is correct config text:
```
modules: [
{
	module: 'MMM-Remote-Control', // HERE NEED TO BE A COMMA
	// uncomment the following line to show the URL of the remote control on the mirror
	position: "bottom_right", // HERE NEED TO BE A COMMA
	// you can hide this module afterwards from the remote control itself
	config: {
		//customCommand: {},  // Optional, See "Using Custom Commands" below
		//customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
		//showModuleApiMenu: true, // Optional, Enable the Module Controls menu
		apiKey: ""        // Optional, See API/README.md for details
		}
},
]
```

**Comment by yassineaqejjaj** [comment]
hi all ! 
i have the same issue. i tried with the coma
`var config = {
	//address: "localhost", // Address to listen on, can be:
	address: "0.0.0.0",                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	//ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	ipWhitelist: [] //to allow all IP addresses
														// or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
`

`modules: [
{
	module: 'MMM-Remote-Control', // HERE NEED TO BE A COMMA
	// uncomment the following line to show the URL of the remote control on the mirror
	position: "bottom_right", // HERE NEED TO BE A COMMA
	// you can hide this module afterwards from the remote control itself
	config: {
		//customCommand: {},  // Optional, See "Using Custom Commands" below
		//customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
		//showModuleApiMenu: true, // Optional, Enable the Module Controls menu
		apiKey: ""        // Optional, See API/README.md for details
		}
},`
can someone please help me out ? 
thanks

**Comment by djay07** [comment]
> hi all !
> i have the same issue. i tried with the coma
> `var config = { //address: "localhost", // Address to listen on, can be: address: "0.0.0.0", // - "localhost", "127.0.0.1", "::1" to listen on loopback interface // - another specific IPv4/6 to listen on a specific interface // - "", "0.0.0.0", "::" to listen on any interface // Default, when address config is left out, is "localhost" port: 8080, //ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses ipWhitelist: [] //to allow all IP addresses // or add a specific IPv4 of 192.168.1.5 : // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"], // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format : // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"], `
> 
> `modules: [ { module: 'MMM-Remote-Control', // HERE NEED TO BE A COMMA // uncomment the following line to show the URL of the remote control on the mirror position: "bottom_right", // HERE NEED TO BE A COMMA // you can hide this module afterwards from the remote control itself config: { //customCommand: {}, // Optional, See "Using Custom Commands" below //customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below //showModuleApiMenu: true, // Optional, Enable the Module Controls menu apiKey: "" // Optional, See API/README.md for details } },`
> can someone please help me out ?
> thanks

at least you could have formatted your question.
Nobody can read this.

**Comment by DaVinki** [comment]
Hi, 

I Believe above errors all have to do with not being able to create an API key. Not sure on how to resolve this though. 

`bash: line 147: /usr/local/bin/node: No such file or directory

Do you want to view instructions on how to configure the module? [Y/n]? n

You should also set an API key in your config section!
It's dangerous to go alone! Take this.
apiKey: ''
I made it just for you.`

**Comment by ember1205** [comment]
Just installed this module today, 12/13/19, and am seeing that the configuration details being presented during the install are still wrong. Is it normal to go NINE MONTHS without someone committing the correct configuration into the project? This is seemingly a very straight-forward item to correct as part of the master.

**Comment by 2wenty2wo** [comment]
Hi everyone, I'm also having this problem. It's not generating a API key.
When I test the API (http://mirrorip:8080/api/test) I get this:
`{"success":false,"message":"Forbidden: API Key Not Provided!"}`

**Comment by Jan-2005** [comment]
Immer noch nicht geändert fehlt besteht weiter modul umbrauchbar !
