### ISSUE TITLE
Issues with Remote Control 

### ISSUE THREAD

**Issue by JTD420** [Jopyth/MMM-Remote-Control#124]
Ever since adding the remote control module I've been having some issues...

The current issue happens every time the screen is supposed to turn off (hide modules/screensaver/power saver?).

Instead, what happens is it hides everything except for the Current Weather and Weather Forecast modules.

This is fixed by going to "Edit View" in the Magic Mirror Menu and enabling all the modules (or the desired ones).

How do I fix this permanently so all modules get hidden/disabled after the timeout and re-enabled once activity is detected again (mouse movement, wake word used, etc)?

Thanks for any help you can give!

**Comment by JTD420** [comment]
This doesn't seem to have fixed the problem either.
Now the issue is still happening and random times however now it's not even responding to voice inputs so requires me going on the remote to edit the view! 

There must be a fix for this? I'm considering removing the Remote Control module until it's resolved :(

**Comment by Jopyth** [comment]
Which module is turning off the screen and how? The Remote Control module itself? Or another module? You say something about voice input?
