### ISSUE TITLE
API doesn’t works

### ISSUE THREAD

**Issue by ezar** [Jopyth/MMM-Remote-Control#127]
Fantastic module!!!

Using v2 cannot use API. When I access to /api appears an error.

**Comment by lawrence-jeff** [comment]
Same here - using the GET example
Cannot GET /api/notification

**Comment by cryptooth** [comment]
Same here...

**Comment by moryoav** [comment]
same here. Any thoughts on this? Tried with or without an api key, didn't make a difference.

**Comment by mlcampbe** [comment]
Same problem here myself. I was wondering if this requires the MMM-Api module to be loaded but when I install that my MM won't even load up.  It fails with an ENOTDIR when trying to open .../modules/package-lock.json/package-lock.json.js

**Comment by Dresch360** [comment]
Having the same issue.
