### ISSUE TITLE
Menu ability to manage action

### ISSUE THREAD

**Issue by bolish** [Jopyth/MMM-Remote-Control#128]
Hi @Jopyth 

Within the custom_menu possibilities ;

Is a `"type":"menu"` able to manage an "action" ?

i.e 

 "id": "Menu_Perso_1",
   "type": "menu",
   "icon": "id-card-o",
   "text": "%%TRANSLATE:CUSTOM_MENU%%",
    "action": "NOTIFICATION",
    "content": {
              "notification": "SLIDESHOW_SHOW",
           }

And then enter this sub-menu to see different other items.

Thanks in advance for support

**Comment by ezeholz** [comment]
Hey! Please explain yourself a little bit more about what you're expecting from the custom menu. I need details from what you actually wanna do. I'm gonna close it now, but feel free to reopen it and keep commenting if you have something more to add.
