### ISSUE TITLE
Error: Cannot find module 'pm2'

### ISSUE THREAD

**Issue by qistoph** [Jopyth/MMM-Remote-Control#130]
With a clean install of MagicMirror on a new system 'Restart MagicMirro²' doesn't work.

An error is shown in the MM log that states `Error: Cannot find module 'pm2'`.

I did mange to fix this, using the following instructions:
```
cd ~/MagicMirror/modules/MMM-Remote-Control
npm link pm2
```

This links the globally installed `pm2` to the local `node_modules` folder.

**Comment by Jopyth** [comment]
Can this be included in the install script?

**Comment by maqlhr** [comment]
the above link command was a gr8 ! it did manage to shutdown the magic mirror. somehow, its not restarting it..

pm2 log says
0|mm  | MMM-Remote-Control customMenu Requested, but file:/home/pi/MagicMirror/config/custom_menu.json was not found
0|mm  | [AMK2] Conversation Completed
0|mm  | PM2 process: restart mm
