### ISSUE TITLE
api actions feedback

### ISSUE THREAD

**Issue by gisteren** [Jopyth/MMM-Remote-Control#135]
Hello,

Is there a way to get feedback from module action? I want to add an alarm to my module, but a few fields are mandatory and I was wondering if I was able to give a fail back when one of these fields are missing.

Regards,

Richard

**Comment by ezeholz** [comment]
Hey! So you probably would need any middleware to being able to send and receive info between modules. With that, would be better for you to send and receive feedback between modules. Cheers and Keep Programming ;D
