### ISSUE TITLE
Icons are gone

### ISSUE THREAD

**Issue by thedoorsfanatic** [Jopyth/MMM-Remote-Control#137]
Since MM update to 2.7.1 all icons are missing

**Comment by pyrosmiley** [comment]
I tried reverting to v1.1.5 of this module, just in case, but that didn't change anything. I'm assuming this has something to do with the MM update to the new fontawesome implementation?

**Comment by BluP62** [comment]
Same issue here with MM 2.7.1. No icons and therefore hard to use.

**Comment by BluP62** [comment]
Try [https://github.com/Jopyth/MMM-Remote-Control/pull/136](url)
This fixed the issue for me. The path to font-awesome has changed.

**Comment by smowk** [comment]
It works!

Thank you @BluP62

**Comment by Jopyth** [comment]
I have not update my MagicMirror for a while. Merged the PR into develop and will make a release soon.
