### ISSUE TITLE
Can't access remote control through phone.

### ISSUE THREAD

**Issue by Payalkundu** [Jopyth/MMM-Remote-Control#138]
Remote control is work from my laptop from which raspberry is controlled. 
But can't access phone or other devices through http: //192.168.xxx.xx:8080/remote.html
How to access through phone? 

Here is my code:

var config = {
address: "0.0.0.0", 
port: 8080,
ipWhitelist: [],

**Comment by Payalkundu** [comment]
Please help me out

**Comment by leekis** [comment]
see

https://github.com/Jopyth/MMM-Remote-Control/issues/133

**Comment by Payalkundu** [comment]
How to setup dhcpcd.comf file?

**Comment by Gonzalo8642** [comment]
I'm also having this problem. Any update?

**Comment by ezeholz** [comment]
@Gonzalo8642 [#133](https://github.com/Jopyth/MMM-Remote-Control/issues/133#issuecomment-483502623)
