### ISSUE TITLE
edit view throws an error

### ISSUE THREAD

**Issue by fieldofgreen** [Jopyth/MMM-Remote-Control#139]
so my menu looks screwed, i read it had something to do with the newest MM update, still pretty new to all of this.
<img width="958" alt="main menu issue" src="https://user-images.githubusercontent.com/49852731/56482179-b8ccab80-6490-11e9-9029-4bc4c22bc89c.png">
I had it working and then I believe I used the Restart button that restarted my pi and now ive got this and have no clue how i broke it.
<img width="948" alt="edit menu issue" src="https://user-images.githubusercontent.com/49852731/56482187-c71ac780-6490-11e9-9a1b-9b5d9587597d.png">
it doesnt help that the edit view didnt let me toggle the modules, but that was a problem for after getting the remote to work. if i knew what log files it meant to look at that would help.

**Comment by fieldofgreen** [comment]
turns out the google tasks module i was using was causing everything to just break. took it out and it works fine now.

**Comment by dngreer46** [comment]
What module was it? I'm getting this same error and have no idea why

**Comment by fieldofgreen** [comment]
https://github.com/jayked/MMM-GoogleTasks/blob/master/README.md

Uhh well I dont have the mirror anymore (let another group member keep it) but if I remember correctly, the google tasks module that i mentioned was that one made by jayked. Honestly I dont remember how that fixed it but something in the google tasks was just breaking everything. Worked fine later until my YouTube bob Ross paintings stopped being able to play the episodes.

Hope this helps, cheers :D
