### ISSUE TITLE
Module works like a charm except for displaying the IP address and some control icons

### ISSUE THREAD

**Issue by GattoJohnny** [Jopyth/MMM-Remote-Control#143]
Hello. I've been using this fantastic module for about half a year now, since MM v2.5. It always worked like a charm, until now. Today I did a fresh install on my RPi 3B+ :
- MM v2.7.1
- MMM-Remote-Control v2.0.0

MMM-Remote-Control is still working fine but 
1) it does not show some control icons in the browser (Firefox, Edge, Chrome), like BACK button, the ON/OFF indicator, Shutdown and Restart symbols etc.

![MMM-Remote-Control-01](https://user-images.githubusercontent.com/47010649/58585057-fa9efd80-8257-11e9-8ba1-a2f0716a4f1b.jpg)

![MMM-Remote-Control-03](https://user-images.githubusercontent.com/47010649/58585066-fe328480-8257-11e9-82d3-ab2d2a135933.jpg)

2) http://ip-of-your-mirror:8080/remote.html is shown instead of actual IP address.

![MMM-Remote-Control-02](https://user-images.githubusercontent.com/47010649/58585086-0be80a00-8258-11e9-95dc-eb8ee01ec591.jpg)

I was reading through other tickets mentioning the same problem, but as fas as I understood they all were revolving around the static IP address and the dhcpcd.conf file. I use dynamic address and I'd like to keep it that way for some reasons.

Please, let me know what info you need and I'll be glad to provide you with all of them.

**Comment by DNA2010** [comment]
what raspberry pi are using, my is raspberry pi 3 B+ magic mirror v 2,7.1 v, remote 2.0.0 v the remote is not working 
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

MAGIC-MIRROR------Module Loaded and Linked-------ELECTRON.JS
MAGIC-MIRROR------Module Loaded and Linked-------APP.JS
MAGIC-MIRROR------Module Loaded and Linked-------SERVER.JS
MAGIC-MIRROR------Module Loaded and Linked-------UTILS.JS
MAGIC-MIRROR------Module Loaded and Linked-------DEFAULTMODULE.JS
Starting MagicMirror: v2.7.1
Loading config ...
MAGIC-MIRROR------Module Loaded and Linked-------DEFAULTS.JS
MAGIC-MIRROR------Module Loaded and Linked-------CONFIG.JS
MAGIC-MIRROR------Module Loaded and Linked-------DEPRECATED.JS
Loading module helpers ...
No helper found for module: alert.
MAGIC-MIRROR------Module Loaded and Linked-------NODE_HELPER.JS-/-UpdateNotification
MAGIC-MIRROR------Module Loaded and Linked-------INDEX.JS
MAGIC-MIRROR------Module Loaded and Linked-------CLASS.JS
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
MAGIC-MIRROR------Module Loaded and Linked-------NODE_HELPER.JS-/-Calendar
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
MAGIC-MIRROR------Module Loaded and Linked-------NODE_HELPER.JS-/-Newsfeed
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Sockets connected & modules started ...
Launching application.

**Comment by GattoJohnny** [comment]
@DNA2010 , I guess you might have overlooked my specification at the beginning of my ticket.

> Today I did a fresh install on my RPi 3B+ :
> MM v2.7.1
> MMM-Remote-Control v2.0.0

It looks like the same as yours, regarding the hardware, OS and module versions. The IP acquiring method can be different, though. Mine is dynamic. However, it is probably not the reason of the missing icons.

**Comment by GattoJohnny** [comment]
ping

**Comment by GattoJohnny** [comment]
l-carado's suggestion in issue 152 (https://github.com/Jopyth/MMM-Remote-Control/issues/152) has cured the "ip-of-your-mirror" problem. By inserting 
`if (notification === "IP_ADDRESSES") { this.addresses = payload; this.updateDom(); }`
in line 64 brought the ip address back.

However, icons are still missing. We can get along without the icons on the left side of Back / Restart / Shutdown etc. But the invisible On/Off switches next to the module names is a real pain.


- MM v2.9.0
- MMM-Remote-Control v2.

**Comment by l-carado** [comment]
@GattoJohnny , 
I nver notice this problem because I always see the module without icons.
The problem is the Awesome font version.
Jopyth for his module used the 4.7.0 version but now the MM is at 5.3.1 version and It seems that  isn't backwards compatible.
I'm not expert in MM fonts but I have an "home made" solution:
- Download all the 4.7.0 font package from awesome site:
[https://fontawesome.com/v4.7.0/get-started/?utm_source=fontawesome4.7](url)
- Expand it in a your favorite folder (may be MMM-remote-Control folder)
- Than modify the line 11 of remote.html file with new path (where you expand the font).
If you expand it in remote-control folder:
` <link rel="stylesheet" type="text/css" href="modules/MMM-Remote-Control/font-awesome-4.7.0/css/font-awesome.min.css">`

Of course make a backup of the original html file...

**Comment by GattoJohnny** [comment]
@l-carado, unlike the fonts, you are REALLY AWESOME! :-))))))))))))
Thanks a lot for the excellent and prompt assistance!
