### ISSUE TITLE
remote.js not loading

### ISSUE THREAD

**Issue by DNA2010** [Jopyth/MMM-Remote-Control#148]
the remote.js file is not link / loading when the mmm-remote-control module is started, can not locate the setting to load the file when the module is started, found API.js link in the node_helper .js file at the bottom "require("./API/api.js")));".  the sendsocketnotification function in the remote.js file is not working, what module should the link for remote.js setup in?

**Comment by DNA2010** [comment]
npm linking problem
pi@raspberrypi:~/MagicMirror $ npm
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/


npm@5.8.0 /usr/share/npm
pi@raspberrypi:~/MagicMirror $ npm -v
5.8.0
pi@raspberrypi:~/MagicMirror $ node -v
v10.15.2
pi@raspberrypi:~/MagicMirror $

**Comment by DNA2010** [comment]
removed npm and reloaded to fix npm WARN npm npm does not support Node.js v10.15.2
still has the problem the remote.js file is not link / loading when the mmm-remote-control module is started
------------------------------------------------------------------------------------------

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.8.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Sockets connected & modules started ...
Launching application.
///////////////// API CreateApiRoutes 1
 ///////////////// API GetApiKey 2
 //////////////////// API GetExternalApiByGuessing 3
 /////////////// API UpdateModuleApiMenu 4
Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
notification = REQUEST_DEFAULT_SETTINGS
addresses = [ '192.168.2.106' ]
notification = CURRENT_STATUS
^CShutting down server...

pi@raspberrypi:~/MagicMirror $ node -v
v10.15.2
pi@raspberrypi:~/MagicMirror $ npm -v
6.10.2
pi@raspberrypi:~/MagicMirror $ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 3572 scanned packages
pi@raspberrypi:~/MagicMirror $

**Comment by ezeholz** [comment]
Hey! So I'm unable to reproduce this bug, because my two instances of Remote Control with MM are working flawless. Can you give more details about it, if you still have the issue?
