### ISSUE TITLE
Device not allowed

### ISSUE THREAD

**Issue by atimon** [Jopyth/MMM-Remote-Control#15]
When following the link I get to a webpage that says:
_This device is not allowed to access your mirror.
Please check your config.js or config.js.sample to change this._
Any help please?

**Comment by jimga150** [comment]
add this to your config file:
```
//allow ALL IPs
ipWhitelist: ["::fff:0.0.0.0/1", "::fff:128.0.0.0/2", "::fff:192.0.0.0/3", "::fff:224.0.0.0/4", "127.0.0.1", "::ffff:127.0.0.1", "::1"],
```
