### ISSUE TITLE
Not initialized

### ISSUE THREAD

**Issue by LLL330** [Jopyth/MMM-Remote-Control#151]
Remote control was working flawlessly until a week or so ago when I continuously got an error screen as shown:

Well that didn't work. Check the MM logs for more details: 
{
   "success": false,
   "status": "error",
   "reason": "unknown",
   "info": "Not initialized, have you opened or refreshed your browser since the last time you started MagicMirror?"
}

I am using an open whitelist and have tried reinstalling the remote control as well as updating both it and my raspberry pi, any and all help with the issue is appreciated.

**Comment by lavolp3** [comment]
Apparently the same issue as mine #147

**Comment by xplod609** [comment]
I have this issue as well

**Comment by johnzaccari04** [comment]
same here

**Comment by jitmo** [comment]
TL;DR, you might need to [upgrade](https://docs.magicmirror.builders/getting-started/upgrade-guide.html) to at least MagicMirror 2.12.0 (released on [2020-07-01](https://github.com/MichMich/MagicMirror/blob/master/CHANGELOG.md#2120---2020-07-01))

Detail: I have just encountered this issue and found the following in the web browser console (by browsing to http://YOUR_MIRROR_IP_ADDRESS:8080):

```
Load script: modules/MMM-Remote-Control//MMM-Remote-Control.js
module.js:471 Check MagicMirror version for module 'MMM-Remote-Control' - Minimum version:  2.12.0 - Current version: 2.11.0
module.js:475 Version is incorrect. Skip module: 'MMM-Remote-Control'
```

**Comment by Nneuland** [comment]
That was absolutely it.  RAIN-MAP was messing things up.   Thank you so much
