### ISSUE TITLE
http://ip-of-your-mirror:8080/remote.html

### ISSUE THREAD

**Issue by GattoJohnny** [Jopyth/MMM-Remote-Control#152]
Dear @Jopyth ,

There are a few "ip-of-your-mirror" issues here and none of them seems to be solved. I'd be grateful if you could give me a hint how to fix it.
It's a fresh MM 2.8.0 install with MMM-Remote-Control 2.0.0.

Please let me know what logs you need.

Cheers, Gyorgy

**Comment by RNSwanson** [comment]
I am having the same issues and unable to resolve them with the posts.  This may be due to my inexperience however I have hit a wall and not sure where to proceed.  I feel like it must be a config issue, however I have tried several different procedures.
address: "0.0.0.0",
port:8080,
ipWhitelist: [],
http://ip-of-your-mirror-8080
If I set anything else I recieve a general error message.  most likely syntax error

**Comment by astronomer-bh** [comment]
I also have this issue on a brand new installation.  I'd like to add that when I find the ip address of my pi, and type it into the url, the module works correctly.  It just doesn't display the url properly on the screen.

**Comment by mesomorf1** [comment]
> 
> 
> I am having the same issues and unable to resolve them with the posts. This may be due to my inexperience however I have hit a wall and not sure where to proceed. I feel like it must be a config issue, however I have tried several different procedures.
> address: "0.0.0.0",
> port:8080,
> ipWhitelist: [],
> http://ip-of-your-mirror-8080
> If I set anything else I recieve a general error message. most likely syntax error

Change the row `address: "0.0.0.0",` to `address: "",` ..that made it start working for me.

But as **astronomer-bh** say, it will still display the "http://ip-of-your-mirror-8080" on the screen, but still working

**Comment by GattoJohnny** [comment]
@astronomer-bh , could you please check if you have the icons or not in the remote control browser? I miss them all:
https://user-images.githubusercontent.com/47010649/58585057-fa9efd80-8257-11e9-8ba1-a2f0716a4f1b.jpg
https://user-images.githubusercontent.com/47010649/58585066-fe328480-8257-11e9-82d3-ab2d2a135933.jpg

**Comment by l-carado** [comment]
@GattoJohnny, I can show the IP address with a little change to MMM-Remote-Control.js.
I'm using an RPi 3B+ with last raspbian and MM 2.9.0
I have inserted the check for notification of IP address at line 64:

`if (notification === "IP_ADDRESSES") {
    this.addresses = payload;
    this.updateDom();
 }`

Of course make a backup of original file before making the change....

**Comment by GattoJohnny** [comment]
@l-carado, thank you for the code. It did the trick, concerning the "ip-of-your-mirror" issue.
