### ISSUE TITLE
Send integer as notification payload

### ISSUE THREAD

**Issue by wakille** [Jopyth/MMM-Remote-Control#155]
Hello,

I want to pass an integer as payload for the page_changed command of the mmm-pages module. But if I try to it with "192.168.0.62:8080/api/notification/PAGE_CHANGED?payload=2" the number always gets parsed as a string. Is it possible to pass the number as integer ?

Thank you for your help!

**Comment by ezeholz** [comment]
Hey! I found this issue, and it's in line to fix it. The problem is that it grabs [everything](https://github.com/Jopyth/MMM-Remote-Control/blob/master/API/api.js#L286) as a string. I have to check if it's possible to send an integer as a payload.

**Comment by majdzik84** [comment]
@ezeholz I will ask shyly.
Is there any chance to fix this? :)

**Comment by ezeholz** [comment]
@majdzik84 Sure there is! This however can partially work using the new custom menus.

Soon I'll fix it, if it's not in December, will be New Year's gift :D

**Comment by ezeholz** [comment]
I just saw the issue raised there. Let me think about a workaround.

**Comment by majdzik84** [comment]
Thanks for one. Works correctly!
