### ISSUE TITLE
Cant make api calls since update

### ISSUE THREAD

**Issue by Maleya** [Jopyth/MMM-Remote-Control#156]
I used to have http://ip-of-pi:8080/api/brightness/200 bookmarked to force the brightness somewhat higher. When I tried it today It returns:

`> Cannot GET /api/brightness/200`

None of the other api calls from [here](https://documenter.getpostman.com/view/6167403/Rzfni66c?version=latest#0fa75ac4-31c4-498c-aeb0-09deef9e7617) seem to work either. 

Im pretty sure this change happened after an npm update but it could be something else spooking. Anyone having similar issues? 

Edit: 
forgot to mention that http://ip-of-pi:8080/remote.html is still working as normal

**Comment by ezeholz** [comment]
Hey! So I'm here willing to solve this issue if you still having it. However I'm not being able to reproduce it at the time. Are you still having this bug? If you have, please feel free to answer and reopen this issue. Cheers :D
