### ISSUE TITLE
No API routes found for alert.

### ISSUE THREAD

**Issue by josopu** [Jopyth/MMM-Remote-Control#158]
Hello there! I am trying to configure the API but I can't get it to work.

curl -X GET http://192.168.1.xxx:8080/api/module/alert/showalert?message=Hello&timer=2000
{"success":false,"info":"No API routes found for alert."}

I did install MM, MM-Remote-Control and MM-Api (all via "Quick Install" and latest master branch version).

config.js:
{
			module: 'MMM-Remote-Control',
			position: 'bottom_left',
			config: {
				// customCommand: {}, // Optional, See "Using Custom Commands" below
				// customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
				// showModuleApiMenu: true, // Optional, Enable the Module Controls menu
				// apiKey: "ba8fg76a8fb8a89t4378trhjk89ay89g", // Optional, See API/README.md for details
			}
		},
		{
			module: 'MMM-Api',
		},

**Comment by ezeholz** [comment]
You can use another API command to send an Alert, like [This one](https://documenter.getpostman.com/view/6167403/Rzfni66c?version=latest#440a40a5-c1a2-4ebb-adc2-2666bf3e5f98)
Also, try to search around that same page, because I don't think that the Api module's gonna do much.

**Comment by ezeholz** [comment]
Hey! So I checked what you're saying, and I'm nnot having any issues related to that. Everything is working as expected. Feel free to reopen this issue if you still having trouble. Cheers ;D

![image](https://user-images.githubusercontent.com/30635862/97629520-01adda80-1a0d-11eb-8bed-2f789e67d0cc.png)
