### ISSUE TITLE
add custom remote buttons to execute shell commands

### ISSUE THREAD

**Issue by LukasBergs** [Jopyth/MMM-Remote-Control#159]
Hello! 

At first I want to say thank you for this awesome module!

What I am trying to do is adding an additional button to my remote. I want to use this button to execute a python script via shell command but I'm not able to get it work. (what i was able to do is customize the "MONITOROFF" command to execute the python script but I would prefer adding additional buttons to my remote)

1) Is this even possible?
2) Do I have to adapt the remote.html, remote.css and remote.js or do I just have to use the "custom_menu.example.json" file?
3) I would highly appreciate if you could support me with tipps or maybe a small tutorial because I am a beginner and haven even used javascript, html and css before.

Thanks a lot!  
Lukas

**Comment by AshDarko** [comment]
Just want to 2nd the above, great module!!

Wondering if you can help, as I am after something very similar.Want to add either a button to the main menu, or (preferably) have a separate *remote-profile.html* page that I can display on a separate device to enable some to select a specific profile.

So i have two problems, (newbie so bear with me):

1. Creation of either a menu button or custom menu page
2. And adding appropriate code to where?

I am using [https://github.com/tosti007/MMM-ProfileSwitcher](url) 

If this needs to be a separate issue i can put this in a new thread no problem. Really hope you or the community can help!

My real end game is to have a physical button ont he side of the mirror which will rotate the profiles, but thats for later, when i at least can get my head round this sending notifications properly and where to put them. Thank you in advance!

**Comment by ezeholz** [comment]
Okay, like there was so much time since this was made. I'm kind of modifying the code right now, and I'm seeing that this repo doesn't have so much of what you guys are saying. So, as soon as I finished with some stuff about Shutdown and Reboot commands, I'll get into this if you guys still need it.
Cheers :D

**Comment by Mathbo12** [comment]
Hello Lukas,

I want to realize exactly the same functionality. If you found a solution, please can you share it here ?

Thanks a lot
Mathieu

**Comment by gkchim** [comment]
@LukasBergs  or @ezeholz could you please help me understand how i can run a custom shell script thanks

**Comment by ezeholz** [comment]
@gkchim You can use [this](https://github.com/Jopyth/MMM-Remote-Control/wiki/Configuration#custom-commands), to understand better. Soon we'll add the same functionality into the custom menus. Cheers! :D

**Comment by gkchim** [comment]
> @gkchim You can use [this](https://github.com/Jopyth/MMM-Remote-Control/wiki/Configuration#custom-commands), to understand better. Soon we'll add the same functionality into the custom menus. Cheers! :D

Thank you - I have managed to add a custom shell command by overwriting the Monitor Status command. Just to confirm - this is the only way of doing it at the moment, is that correct?

So at the moment, i cannot add a separate new custom command to execute a shell script?  (even without it listed in the menu)

**Comment by ezeholz** [comment]
@gkchim That's correct. Sorry for the inconvenience.

**Comment by testbughub** [comment]
I would love this feature. 
I just spent the last hour trying to get controls for my 433MHz RF outlets, when I noticed this issue.
If I were more knowledgeable in javascript, I'd make my own module, but I'm relying on bash for that at the moment.

**Comment by ezeholz** [comment]
Just an update for all of you, I was thinking about this, and trying to do the best to bring it to you guys this feature, but also I don't want that this became a security matter, so I'll implement this using the config from the module, and bring the command every time it's called. With that, we'll be doing the same as using the monitorStatus commands, but with custom exec commands. That way, you can't send a command to execute remotely as a payload, but actually send the identifier for it to run. That's the most secure way to implement it. I'll let you know when it's ready. Cheers :D

**Comment by gkchim** [comment]
You are a superstar! This will be by far the best feature in MM2

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by testbughub** [comment]
You just made my day! Thank you!

**Comment by ezeholz** [comment]
The implementation it's done. You guys can use the API to call the command you need to execute. I need to add a few things more, like the menu and the ability to use it with the custom menu. But the shell it's working and it's functional.
Remember that the develop branch may contain bugs. If you find a bug, please let me know! Cheers :D

**Comment by testbughub** [comment]
Man, you work fast! I love it!

**Comment by gkchim** [comment]
You are amazing Ezequiel! Thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gkchim** [comment]
Hi @ezeholz ,
So, I have added the below to my config file. However,  I am not sure how to trigger the command lightsOffCommand.

```
config: {
				customCommand: { 

					monitorStatusCommand: 'cd ./MagicMirror; python3 send.py -p 396 -t 1 11717633',
					lightsOffCommand: 'cd ./MagicMirror; python3 send.py -p 396 -t 1 11717635',
						},
```

if i go to :8080/api/monitor/status  then the 1st custom command  is exwcuted fine, However if i go to :8080/api/lights/off  I get  an error. Is there a step i have missed or have i approached this the wrong way?

**Comment by ezeholz** [comment]
@gkchim hey! So the Remote doesn't have an API that calls lights. U should check the API Docs for the available options using `/api/docs `

The endpoint you need is `/api/command/lightsOffCommand`

Remember to set an API key, or disable the security beforehand. Cheers :D

**Comment by testbughub** [comment]
Just a quick question;
Is this module still using Font-Awesome 3? I tried using an icon from 4, but it's just blank.

**Comment by ezeholz** [comment]
@testbughub Remote Control use the Font Awesome from the MagicMirror itself. The last version that they're using seems to be the 4th though.

**Comment by testbughub** [comment]
Weird. I guess I did something wrong. I'll look into this some more. Thanks for the quick reply!

**Comment by gkchim** [comment]
Hi @Jopyth/MMM-Remote-Control<mailto:reply@reply.github.com>

My endpoint is endpoint you need is /api/command/lightsOffCommand

Is it now possible to ass these commands to a custom menu?
if i wanted to call on this command from a different module using notifications - how can i do this please / what notification do i use?

________________________________

**Comment by ezeholz** [comment]
You can totally use both options.

To add it into the custom menu you should specify the `action` as `COMMAND` and inside `content` you should add a `'command': 'lightsOffCommand'`

To call it from another module, you should use the REMOTE_ACTION notification, and add as a payload:
```js
{
'action': 'COMMAND',
'command': 'lightsOffCommand',
}
```

**Comment by gkchim** [comment]
Thank you, does this change if I switch on secure endpoints and use an API key?

Trying to integrate this to MMM-AlexaControl

Thanks again

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ezeholz** [comment]
Secure Endpoints and API Key doesn't apply from one module to another, if you're sending notifications between them.

Those only apply if you're gonna use the `/api/command/lightsOffCommand`

**Comment by gkchim** [comment]
Hi I have tried the below, but cannot get it to work is the right format/syntax:

http://192.168.1.16:8080/api/command/VanityOn&apiKey=9ddh31ddjkjkjdkjd9a

I get :

{"success":false,"message":"Forbidden: API Key Not Provided!"}

________________________________

**Comment by ezeholz** [comment]
@gkchim Apikey it's defined wrong, you should use `?` in the first variable. Should be:

http://192.168.1.16:8080/api/command/VanityOn?apiKey=xxxxxx

Also, remember to change your apiKey, just for safety.
