### ISSUE TITLE
Power -> restart MagicMirror not working

### ISSUE THREAD

**Issue by hypoflex** [Jopyth/MMM-Remote-Control#160]
After clicking restart in the remote control it does kill the process and with that the server.
but it does not come back up

(blurred out calendar)
![image](https://user-images.githubusercontent.com/36196198/69509924-21a26780-0f3b-11ea-8c7e-3c63e3734864.png)

**Comment by hypoflex** [comment]
![image](https://user-images.githubusercontent.com/36196198/69510052-907fc080-0f3b-11ea-81ef-f88f4215228e.png)

**Comment by ezeholz** [comment]
It's a bug already reported #118 
#126 for the working out method
