### ISSUE TITLE
Unable to embed in panel iframe

### ISSUE THREAD

**Issue by Andoramb** [Jopyth/MMM-Remote-Control#161]
Hi and thanks for the module :)

I'm struggling to embed the remote.html page into a different project (Home Assistant).

Accessing the remote.html works using caddy server with https.
However once I add it to the Home Assistant Panel Iframe, the dev console returns: 
`Refused to display 'https://xx.yy.duckdns.org:port/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

I tried adding to the Caddyfile:
`header_downstream -X-Frame-Options`
but it still refuses to display the page.

-------------------------------------
One more thing I've noticed:
At the Manual Install section:

- (2) Add the module to your config/config.js

      {
         module: 'MMM-Remote-Control'   <- comma is missing at the end of line

May be helpful for others.

Thanks!

**Comment by ezeholz** [comment]
Hey!
Given the time, I hope this problem was resolved long ago.
Feel free to open a new issue if you feel like it's not that way.
Cheers :D

**Comment by testbughub** [comment]
Hate to bring up an old issue, but I just tried adding the controls with MMM-iFrame, and ended up with the same error.
I've tried multiple things, but all failed.
Is there a way do add the controls to the screen?
