### ISSUE TITLE
Symbols from FontAwesome missing in menu

### ISSUE THREAD

**Issue by Snille** [Jopyth/MMM-Remote-Control#165]
Hi, I get this error on both my installations in the "development" mode in Chrome...
Refused to apply style from 'http://X.X.X.X:8080/vendor/node_modules/font-awesome/css/font-awesome.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
You can also see that the Symbols are missing in the menu:
![image](https://user-images.githubusercontent.com/1011699/71127514-8cb62580-21eb-11ea-9579-ea6d089d0d2e.png)

Have I forgotten something...
If I try to find the file in the path above, it does not exist, I believe the the path should be: ~/MagicMirror/vendor/node_modules/@fortawesome/fontawesome-free/css)
![image](https://user-images.githubusercontent.com/1011699/71127863-2aa9f000-21ec-11ea-8970-e7eef9ff5607.png)

This is a fresh install, so all things should be there. :)
Or am I missing something?

**Comment by mihanich** [comment]
Hi there!
Got same error (no fontawesome npm module installed), but after manual installation got this - 
![Screenshot_20191231_122416](https://user-images.githubusercontent.com/29480208/71618494-784d3200-2bc8-11ea-88a7-2fa2f1c9080e.png)
Is there any way to make icons back?
Also please note that way to fontawesome in remote.html is broken and need to be corrected after npm module install.

**Comment by mihanich** [comment]
fixed:
1. install font-awesome with `npm i font-awesome`
2. change path to css in remote.html to `modules/MMM-Remote-Control/node_modules/font-awesome/css/font-awesome.min.css`
Profit)
![Screenshot_20191231_131554](https://user-images.githubusercontent.com/29480208/71619949-aeda7b00-2bcf-11ea-90ac-d6d56e434179.png)
