### ISSUE TITLE
Getting error code SSL_ERROR_RX_RECORD_TOO_LONG in Firefox when trying to connect from laptop

### ISSUE THREAD

**Issue by android9pie2** [Jopyth/MMM-Remote-Control#166]
When I try to go to the website, it gives me an SSL error, and I don't know why. This problem was brought up before but it was never answered. What can I do to fix this, and can you please respond to the other gentleman who asked the same question, please?

**Comment by ezeholz** [comment]
I'm not familiarize with SSL at all, but [this](https://www.thesslstore.com/blog/ssl_error_rx_record_too_long/) link may help. Would you mind to explain a little bit about that? Like how was the instalation, and if the is any error on the terminal. Thanks ;D
