### ISSUE TITLE
Automatic install destroys config.js

### ISSUE THREAD

**Issue by jennech** [Jopyth/MMM-Remote-Control#167]
Hi,

I did the automatic install. 
Looked in the config.js und saw the lines mixed up - marked with apostrophes ""

<img width="536" alt="image" src="https://user-images.githubusercontent.com/37270016/71925766-137a7480-3192-11ea-986b-315f69c3424d.png">

**Comment by ezeholz** [comment]
I don't see any trouble with that file. Could you explain a little bit more please?
