### ISSUE TITLE
Remove Features

### ISSUE THREAD

**Issue by Mert4531** [Jopyth/MMM-Remote-Control#170]
Hi there
I wanna remove some features on remote control module. Such as Toggle Fullscreen, Minimize Browser and Open Devtools. Can these features be removed without affecting the operation of the module?

**Comment by ezeholz** [comment]
Of course you can! I mean, they actually wouldn't show up in the menu, if that's what you want. You can erase them under the remote.html file, over [here](https://github.com/Jopyth/MMM-Remote-Control/blob/2daec303f5ddea8288daedfa2941dc9e9bba4d8b/remote.html#L126) most exactly.

If what you want is erase them in a way more deeper, you can take a look at node_helper.js, over [here](https://github.com/Jopyth/MMM-Remote-Control/blob/2daec303f5ddea8288daedfa2941dc9e9bba4d8b/node_helper.js#L745)

I hope that resolves your issue. Please don't forget to close this once you feel like you actually resolves this. Cheers ;D
