### ISSUE TITLE
Turn modules off and on in C# application

### ISSUE THREAD

**Issue by gielekee** [Jopyth/MMM-Remote-Control#171]
For a school project we are using MMM-Remote-Control. It works perfect and we can view the index.html in the app but we want to have custom buttons inside the app that can turn a module on or off and not directly through the HTML website. 

Is there any option for this?
Or someone who can tell where we need to look :)

**Comment by ezeholz** [comment]
I think I kinda understand what you guys want. Of course, this is not the perfect module to look after that, but I'm gonna let a link down below of another module that may help you.
[MMM-ModuleToggleButton](https://github.com/balassy/MMM-ModuleToggleButton)

I didn't find another one like that, but I encourage to find the one that fits perfect for your proyect in [MagicMirror² 3rd Party Modules](https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules)

Also, don't forget to close this issue right after you find the perfect module.
Cheers on your proyect! ;D
