### ISSUE TITLE
./installer.sh: line 148: /usr/local/bin/node: No such file or directory

### ISSUE THREAD

**Issue by patientx** [Jopyth/MMM-Remote-Control#172]
I installed mm2 to a rpi2b yesterday. Installed a bunch of modules everything is working perfectly except remote control :(

At first I installed the module normally, with npm install and added the needed lines in the config.js but this leads to : config.js : there are errors in config.js please clean it with linter etc. 
So I tried running ./installer.sh and again everything installed the only message is 
"Update finished!
./installer.sh: line 148: /usr/local/bin/node: No such file or directory
"
What do I do ?

**Comment by przypieczony** [comment]
I am pretty sure you are missing a comma at the end of the module name in config.js.

`{
    module: 'MMM-Remote-Control',
    config: {
    }
}`
It should be corrected in docs

**Comment by patientx** [comment]
LOL. Thanks ! That was it !
