### ISSUE TITLE
Magic Mirror not restarting

### ISSUE THREAD

**Issue by AlexDunn7** [Jopyth/MMM-Remote-Control#173]
Upon restarting MagicMirror via the mobile web interface I get this error,

`0|mm  | [14:08:18.859] [LOG]    
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [14:08:18.860] [ERROR]  { Error: Cannot find module 'pm2'
0|mm  |     at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
0|mm  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm  |     at Function.Module._load (internal/modules/cjs/loader.js:528:25)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm  |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm  |     at Class.controlPm2 (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:867:23)
0|mm  |     at Class.executeQuery (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:654:22)
0|mm  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:1009:26)
0|mm  |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
0|mm  |     at Socket.emit (events.js:182:13)
0|mm  |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
0|mm  |     at process._tickCallback (internal/process/next_tick.js:61:11)
0|mm  |  code: 'MODULE_NOT_FOUND' }
0|mm  | [14:08:18.863] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [14:08:18.864] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm  | [14:08:49.016] [LOG]    
0|mm  | MMM-Remote-Control customMenu Requested, but file:/home/pi/MagicMirror/config/custom_menu.json was not found
`

**Comment by mihanich** [comment]
Hi @AlexDunn7 !
I'm not sure how to get such error, but seems you miss to npm install module.
Can you please recheck your installation and add more details in case it would not help.
Cheers)

**Comment by AlexDunn7** [comment]
@mihanich 
I got the same error again. I'm not sure what other details you want?
I went to the remote control directory and ran npm install.
Thanks

**Comment by mihanich** [comment]
> @mihanich
> I got the same error again. I'm not sure what other details you want?
> I went to the remote control directory and ran npm install.
> Thanks

1. How you install MagicMirror (Docker, node)
2. Whisch way you install (manually, script)
3. Are you using pm2 or kiosk mode

Currently install third time on third instance - everything goes fine.

**Comment by ezeholz** [comment]
I don't even know that MagicMirror has his own tutorial about this, and it's not specified when we come to RemoteControl.

Here: [Auto-Starting MagicMirror](https://github.com/MichMich/MagicMirror/wiki/auto-starting-magicmirror)

Maybe that helps this problem.
