### ISSUE TITLE
Console log in remote control js

### ISSUE THREAD

**Issue by bimbim2401** [Jopyth/MMM-Remote-Control#174]
Hello

thanks for your work, it s very pleasant.

I am juste finding a mistake wich don t let send notification to your module in the remote-control.js in line 43 you have a console.log which is not permitted here.

Can you please correct for other users

thanks

**Comment by ezeholz** [comment]
Hey!

I saw what you're saying, exactly [here](https://github.com/Jopyth/MMM-Remote-Control/blob/2daec303f5ddea8288daedfa2941dc9e9bba4d8b/MMM-Remote-Control.js#L43), what's the problem there? I mean, I think that could run just fine.
