### ISSUE TITLE
Can't get Remote-Control to react on commands received from MMM-MMQTBridge

### ISSUE THREAD

**Issue by fribse** [Jopyth/MMM-Remote-Control#176]
I've tried setting up a few commands like

MONITOROFF
MONITORON
BRIGHTNESS
RESTART
MONITORSTATUS

But no matter what I send through the MQTTBridge nothing happens.
The MQTTBridge receives messages from an MQTT Broker, and relays them as notifications.
If I send the MONITORSTATUS command I see an uncaught exception in the log.

https://forum.magicmirror.builders/topic/12230/mmm-mqttbridge

**Comment by ezeholz** [comment]
All the commands are working on the API of Remote-Control? Did you use a custom command for your monitor? This proyect is quite dead, so there's no one answering in all of this issues. Let me search into the code if there is any "more verbose debug" option.

**Comment by fribse** [comment]
Hi @ezeholz 
Oh, I wasn't aware it was dead, that's very sad.
I've set up a few REST commands in my Home Assistant, and they work.
They work nicely:

  turn_off_mm_screen:
    url: 'http://x.y.z.v:8080/api/monitor/off'
  turn_on_mm_screen:
    url: 'http://x.y.z.v:8080/api/monitor/on'
  dim_mm_screen:
    url: 'http://x.y.z.v:8080/api/brightness/75'
  undim_mm_screen:
    url: 'http://x.y.z.v:8080/api/brightness/100'

**Comment by ezeholz** [comment]
Hey! I hope everything goes fine.
I think that this issue is now solved, so I'm gonna close it. Feel free to open a new one if you need more help.
Keep Programming ;D
