### ISSUE TITLE
you forget the "," in readme.md

### ISSUE THREAD

**Issue by wlmqpsc** [Jopyth/MMM-Remote-Control#177]
Hi!
At the second row module:'MMM-Re.......'
this is right haha!
`{
    module: 'MMM-Remote-Control',
    // uncomment the following line to show the URL of the remote control on the mirror
    // , position: 'bottom_left'
    // you can hide this module afterwards from the remote control itself
    config: {
        customCommand: {},  // Optional, See "Using Custom Commands" below
        customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
        showModuleApiMenu: true, // Optional, Enable the Module Controls menu
        apiKey: "",         // Optional, See API/README.md for details
    }
},`

**Comment by ezeholz** [comment]
That's an error already in a pull request. But because this repository is dead, no one merged that. 
#149

**Comment by radokristof** [comment]
@ezeholz What about creating a fork of this?
I'm happy to create it and merge all these PRs there...

**Comment by TheLukaBoss** [comment]
Yes, that tricked me out, just spent 60 mins trying to fix! Thanks!
