### ISSUE TITLE
API Key specified in header not working

### ISSUE THREAD

**Issue by doctorfree** [Jopyth/MMM-Remote-Control#179]
Specifying a valid API key in the URL works but following the example in the doc for specifying an API key in the header of the request does not work. After examining the source code I changed "Authentication:"  to "Authorization:" and calls work.

It appears to be documented correctly in the Postman example.

I believe the example in the API Readme needs to be modified from:

-H 'Authentication: apiKey bc2e979db92f4741afad01d5d18eb8e2' \

to:

-H 'Authorization: apiKey bc2e979db92f4741afad01d5d18eb8e2' \

**Comment by ezeholz** [comment]
This repository is dead, but you can add a Pull Request to help others, as the original dev is not into this proyect anymore.

**Comment by val77310** [comment]
> Specifying a valid API key in the URL works but following the example in the doc for specifying an API key in the header of the request does not work. After examining the source code I changed "Authentication:" to "Authorization:" and calls work.
> 
> It appears to be documented correctly in the Postman example.
> 
> I believe the example in the API Readme needs to be modified from:
> 
> -H 'Authentication: apiKey bc2e979db92f4741afad01d5d18eb8e2' \
> 
> to:
> 
> -H 'Authorization: apiKey bc2e979db92f4741afad01d5d18eb8e2' \

Hello i replace in config.js the api key with him example but still doesnt work any idea ?
