### ISSUE TITLE
unable to access

### ISSUE THREAD

**Issue by bvbking09** [Jopyth/MMM-Remote-Control#18]
Hey,
I'm trying to access a remote interface. When I type the URL in in my mobile phone it says: This device is not allowed to access your mirror. How can I access it? When I type this (http://192.168.ipOf.myRaspberry:8080/remote.html) in my browser it doesnt work..
Is it caused by Proxy, Firewall etc.?
Can you please help me? :D 
Thank you!

**Comment by israel05** [comment]
Do you have in your config/config.js an ip list of trusted IPs?

**Comment by bvbking09** [comment]
Hey israel05, what is the command for it? What do I have to add inn the config file? Thank you!

**Comment by israel05** [comment]
edit your config/config.js file and then verify that the it looks something like this and all the rest.

/* Magic Mirror Config Sample
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 */

var config = {
        port: 8080,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1","::ffff:192.168.0.1/16", "::1"],

        language: 'es',
        timeFormat: 24,
        units: 'metric',

**Comment by bvbking09** [comment]
And now I have to add the IP address which the mirror shows me? Like this: ipWhitelist ["127....... ....,"::1", "192.168......."], 
Is it correct?

**Comment by israel05** [comment]
Well, lets star from the beggining,  in your original post you say..
(http://192.168.ipOf.myRaspberry:8080/remote.html) 
I know that you have to be very cautious when posting your info, but that kind of adress is only accesible in your LAN, if any of us type your 192.168.0.10 or whatever it is what we will see will be our magicmirrors, phones, compueters, prints... So the line you have to add to the first part of thee config.js is that one
ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1","::ffff:192.168.168.ipOf.myRaspberry/16", "::1"]

Have fun!

**Comment by bvbking09** [comment]
OK i don't get it. I will now write down mi IPs. I would be very thankful if you give me the code? hahaha IP of my mobile phone: 192.168.200.14
IP of my raspberry: 192.168.200.87
What do i have to add now in ipWhitelist [....],
???
Thank you!

**Comment by bvbking09** [comment]
OK I made it. Thank you very much israel05.!!!

**Comment by israel05** [comment]
You are welcome.
