### ISSUE TITLE
Support for displays/devices running Maggic Mirror in client only mode

### ISSUE THREAD

**Issue by jpcaldwell30** [Jopyth/MMM-Remote-Control#180]
Currently is seems like its only possible to preform some of the device actions locally (only on the device running the server). EG: refreshing the display, shutting down the raspberry pi, etc. Is there anyway we could add the ability to control these functions when running in client only mode? For my setup, i have the magic mirror running in server only mode in a docker container on one raspberry pi and another much older raspberry pi actually running the display. I would like to be able to control the remote client only raspberry pi using this module. I have already setup custom commands to turn the display on and off by forwarding the commands to the raspberry pi using ssh. I think if there was an option to run all commands remotely using ssh that would allow for control of devices running magic mirror in client only mode.

**Comment by ezeholz** [comment]
Hey! So, this issue it's a little bit old so I'm gonna close it now. Anyways, answering to your question, you can use the remote itself to send commands through your browser, or also with the implementation of the API added into 2.0
Feel free to open a new issue if you feel like your question wasn't answered correctly, or if you need more help. :D
