### ISSUE TITLE
After the update my magicmirror started to not work??

### ISSUE THREAD

**Issue by DhruvTube** [Jopyth/MMM-Remote-Control#187]
So I updated the magicMirror and then whenever I tried to use it the remote side on my phone say LOADING... and when I look at the logs on the raspberry pi it says:
error: object file .git/objects/04/148cf06af50f12c78c5a8d9757f632e6025686 is empty
fatal: loose object 04148cf06af50f12c78c5a8d9757f632e6025686 (stored in .git/objects/04/148cf06af50f12c78c5a8d9757f632e6025686) is corrupt
fatal: The remote end hung up unexpectedly

**Comment by alomar-mac** [comment]
https://github.com/Jopyth/MMM-Remote-Control/issues/185

**Comment by alomar-mac** [comment]
The solution is from here (https://github.com/Jopyth/MMM-Remote-Control/issues/185)

**Comment by DhruvTube** [comment]
I cannot find js/socketclient.js

**Comment by DhruvTube** [comment]
> The solution is from here (#185)
