### ISSUE TITLE
Black Screen on IP:8080 in Edge

### ISSUE THREAD

**Issue by Hein-Jan** [Jopyth/MMM-Remote-Control#19]
While using MMM-Remote-Control, a black screen occurs on IP:8080 in Edge. IP:8080/remote.html does work. IP:8080 gives a copy of the mirror in Chrome.

Edge version: Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

a (anonymised copied of my config.js is attached.
[config.txt](https://github.com/Jopyth/MMM-Remote-Control/files/721985/config.txt)

**Comment by Jopyth** [comment]
Hopefully this gets fixed on the main project: https://github.com/MichMich/MagicMirror/issues/639
