### ISSUE TITLE
The Update function does not work

### ISSUE THREAD

**Issue by lolkaese1** [Jopyth/MMM-Remote-Control#193]
The remote.html Shows 2 updates. After clicking on one of them an error Shows up :

Well that didn't work. Check the MM logs for more details: 
"success": false,
   "status": "error",
   "reason": "unknown",
   "info": {
      "task": {
         "concatStdErr": false,
         "format": "utf-8",

For both updates it is the same error.
Can Anybody help me with this ?

**Comment by dvbit** [comment]
Same over here

**Comment by dvbit** [comment]
Solved in isseu 185

**Comment by ezeholz** [comment]
Looks like #185 it's the issue. Try that solution, and open a new issue if you feel like you need more help. Cheers :D
