### ISSUE TITLE
Remote on Web Browser Not Working

### ISSUE THREAD

**Issue by w113msh** [Jopyth/MMM-Remote-Control#195]
I followed the instruction for MMM-Remote-Control; however, when I load remote.html into the web browser and it loads, none of the buttons work.  When I go into menus, it only says loading.

Any ideas on how to fix? 

**attached are 2 screenshots**
![86526A6E-F596-4834-941F-98681321F7FF](https://user-images.githubusercontent.com/65371724/81989741-ce68c200-960b-11ea-89db-195d9983e2df.jpeg)
![B4AF335F-4CF8-42B2-967F-92406C121A9D](https://user-images.githubusercontent.com/65371724/81989744-cf015880-960b-11ea-998e-5b46126ce75a.jpeg)

**Comment by marco97233** [comment]
bonjour, idem j ai le meme problème.

**Comment by liquidevo** [comment]
I am having the same issue , I just Installed the module today on a fresh raspi 4 and got the same from laptop and phone, does not do anything please help 

thank you

**Comment by w113msh** [comment]
Thanks to khassel from another thread, the fix is ssh into your pi:

Cd MagicMirror/js/
Sudo nano socketclient.js

Replace

	// Private Methods
	self.socket = io("/" + self.moduleName, {
		path: window.location.pathname + "socket.io"
	});

With

	// Private Methods
        self.socket = io("/" + self.moduleName);


After that it worked for me.  Again this fix was from khassel (give credit where credit is due)

**Comment by robertybob** [comment]
I'm getting an error when I do this 

> 
> 'Magic Mirror Menu
> 
> If you see this message, an error occured whe loading the javascript file....'

This is my js file:
```
/* global io */

/* Magic Mirror
 * TODO add description
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 */
var MMSocket = function (moduleName) {
	var self = this;

	if (typeof moduleName !== "string") {
		throw new Error("Please set the module name for the MMSocket.");
	}

	self.moduleName = moduleName;

	// Private Methods
	var base = "/";
	if (typeof config !== "undefined" && typeof config.basePath !== "undefined") {
		base = config.basePath;
	}
    self.socket = io("/" + self.moduleName);
	});
	var notificationCallback = function () {};

	var onevent = self.socket.onevent;
	self.socket.onevent = function (packet) {
		var args = packet.data || [];
		onevent.call(this, packet); // original call
		packet.data = ["*"].concat(args);
		onevent.call(this, packet); // additional call to catch-all
	};

	// register catch all.
	self.socket.on("*", function (notification, payload) {
		if (notification !== "*") {
			notificationCallback(notification, payload);
		}
	});

	// Public Methods
	this.setNotificationCallback = function (callback) {
		notificationCallback = callback;
	};

	this.sendNotification = function (notification, payload) {
		if (typeof payload === "undefined") {
			payload = {};
		}
		self.socket.emit(notification, payload);
	};
};

```
