### ISSUE TITLE
Commands not functioning

### ISSUE THREAD

**Issue by hm1234** [Jopyth/MMM-Remote-Control#198]
I have just installed the module however it does not seem to be functioning. I tried using the remote page to restart magicmirror and it did nothing. Also just has the rotating circle in modules page does nothing after it.

**Comment by agastyashr** [comment]
having the same issue, not sure where i messed up

**Comment by Gr3yG00se64** [comment]
I'm currently struggling with the same thing. I saw that it hasn't been updated in a while, is it still being supported?

**Comment by abhinavdrolia** [comment]
https://github.com/Jopyth/MMM-Remote-Control/issues/195
Please refer this.

**Comment by ezeholz** [comment]
Hey! So, as you guys can see, this project is no longer maintained by the author. There are a few PR that solve those issues you're having. I managed to pull those together into my fork, so you guys can check out and create an issue over there if you still having some problems.

Cheers :D
