### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by drk-geek** [Jopyth/MMM-Remote-Control#199]
Hi,
Its great work, but I am unable to use due to some syntax error. Just installed and add following in config.js file
========================================================================
{
    			module: 'MMM-Remote-Control'
    			// uncomment the following line to show the URL of the remote control on the mirror
    			// , position: 'bottom_left'
    			// you can hide this module afterwards from the remote control itself
    			config: {
        			customCommand: {},  // Optional, See "Using Custom Commands" below
        			customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
        			showModuleApiMenu: true, // Optional, Enable the Module Controls menu
        			apiKey: "",         // Optional, See API/README.md for details
    			}
		 },
==================================================================
I got the following error:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
1|mm  | WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:43
1|mm  |     			config: {
1|mm  |     			^^^^^^
1|mm  | SyntaxError: Unexpected identifier
1|mm  |     at Module._compile (internal/modules/cjs/loader.js:722:23)
1|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
1|mm  |     at Module.load (internal/modules/cjs/loader.js:645:32)
1|mm  |     at Function.Module._load (internal/modules/cjs/loader.js:560:12)
1|mm  |     at Module.require (internal/modules/cjs/loader.js:685:19)
1|mm  |     at require (internal/modules/cjs/helpers.js:16:16)
1|mm  |     at loadConfig (/home/pi/MagicMirror/js/app.js:69:12)
1|mm  |     at App.start (/home/pi/MagicMirror/js/app.js:210:3)
1|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:115:7)
1|mm  |     at Module._compile (internal/modules/cjs/loader.js:786:30)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
I just copy/paste it,

**Comment by drk-geek** [comment]
hello anyone here to reply ?

**Comment by skyshaddow** [comment]
Hi,

I had the same issue, i found the resolution on another post, there is a few commas missing.

Try This:

{
module: "MMM-Remote-Control",
// uncomment the following line to show the URL of the remote control on the mirror
// , position: "bottom_left",
// you can hide this module afterwards from the remote control itself
config: {
customCommand: {}, // Optional, See "Using Custom Commands" below
customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
showModuleApiMenu: true, // Optional, Enable the Module Controls menu
apiKey: "", // Optional, See API/README.md for details
}
},
