### ISSUE TITLE
Using to control Pi 7in display

### ISSUE THREAD

**Issue by StuBall21** [Jopyth/MMM-Remote-Control#201]
Thanks for a great module. I have this working, but cannot use the commands to turn the monitor on/off as I am using a Raspberry Pi 7in display. I have the commands to turn this on and off and they work when entered via command. But I cannot get it to work in the config file. Any Noob help would be most welcome.
My config file looks like this..
  module: 'MMM-Remote-Control',
    // uncomment the following line to show the URL of the remote control on the mirror
                        position: "bottom_left",
    // you can hide this module afterwards from the remote control itself
                        config: {
                                customCommand: {
                                        monitorOnCommand: "sudo -E sh -c 'echo 0 > /sys/class/backlight/rpi_backlight/bl_power'", //command to turn  7in display on
                                        monitorOffCommand: "sudo -E sh -c 'echo 1 > /sys/class/backlight/rpi_backlight/bl_power'", //command to turn 7in display off
                                                },
 // Optional, See "Using Custom Commands" below
                                customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
                                showModuleApiMenu: true, // Optional, Enable the Module Controls menu
                                apiKey: "",         // Optional, See API/README.md for details
                        }

**Comment by ezeholz** [comment]
Hey! So, the problem you're having is that this module relies not only in turning on and off, but also uses statusCommand in every step. You can check out my fork or my PR, where I change a few files and give this problem a solution.

Reach out to me again if you need any help. Cheers :)
