### ISSUE TITLE
Site Can not be reached

### ISSUE THREAD

**Issue by drk-geek** [Jopyth/MMM-Remote-Control#202]
fresh installation
can not open web page on http://192.168.10.110:8080/remote.html
see the screen shots
![Screenshot_2020-06-08_22-32-01](https://user-images.githubusercontent.com/63916817/84062098-6920aa80-a9d8-11ea-8d01-6ad896a9f166.png)
![Screenshot_2020-06-08_22-33-00](https://user-images.githubusercontent.com/63916817/84062156-6e7df500-a9d8-11ea-87d2-f1fdd5a17d09.png)
![Screenshot_2020-06-08_22-33-24](https://user-images.githubusercontent.com/63916817/84062193-7178e580-a9d8-11ea-86c2-7b53975d2af7.png)
![Screenshot_2020-06-08_22-34-19](https://user-images.githubusercontent.com/63916817/84062223-7342a900-a9d8-11ea-9821-cd71aaff5992.png)

**Comment by eskiiom** [comment]
Hello,
same error on the mirror here, it says ip-of-you-mirror instead of its real ip address.
@drk-geek maybe you have unreachable site because you are using chrome and it tries to use HSTS. Did you try with an other browser ?

For my part it says "cannot display the page".
THanks

**Comment by drk-geek** [comment]
hi @eskiiom I tried both firefox and chorme on desktop, safari on iphone and mac, IE on win, same output,
something nasty happening somewhere, can't figure it out. huh

**Comment by eskiiom** [comment]
hi @drk-geek so you say you can ssh to your magicmirror but not display it ?
did you update it recently ? there is an extra step 'npm install' after 'git pull'
what does 'pm2 show mm' says ?

**Comment by mayank-pratap-singh** [comment]
I am facing the same issue. I guess the module is no more supported.

**Comment by 52-65-65-63-65** [comment]
I have the same problem 
![Remote](https://user-images.githubusercontent.com/40191393/86210406-e8f4fb80-bbb7-11ea-8925-8b3d8f600f56.JPG)
but if you type in the terminal of your raspberry pi
hostname -I
you will get an IP address, replace 
http://ip-of-your-mirror:8080/remote.html
with the number that the terminal says and it should work.
it did for me, I'm not sure why it doesn't show that, but that's what worked for me.

**Comment by Fifteen15Studios** [comment]
Hey guys, I was able to fix this by changing a line in the config.js file from:

    address: "localhost",

to:

    address: "0.0.0.0",

By default it's only listening to the loopback address, which means it can only accept "remote" connections from itself. This lets it listen on all interfaces.

If, instead, you only want it to listen on one interface (for example, just the wired interface, or just the wireless interface) then replace `0.0.0.0` with the IP of that interface.

**Comment by ezeholz** [comment]
Feel free to open a new issue if you guys need any help into this. I'm gonna close this issue now.
