### ISSUE TITLE
So I did the Quick Install, bash -c "$(curl -s https://raw.githubusercontent.com/Jopyth/MMM-Remote-Control/master/installer.sh)", so I don't have to so anything listed under Manual Install?

### ISSUE THREAD

**Issue by Pszoom** [Jopyth/MMM-Remote-Control#207]
I am trying to configure my ipWhitelist for my remote. My Xfinity router supplies ipaddresses for all of my devices on my local network, from 10.0.0.2 to 10.0.0.254. I have my devices set up via my router to keep the ipaddresses for each device fixed so the ipaddress does not change every time a device reboots, it will keep the same ipaddress. I have my whitelist set up with my ipaddress for my iphone, 10.0.0.150 and my PC, 10.0.0.170. This is the error message I get when I try to access the remote via url
http;//10.0.0.131:8080/remote.html, (This device is not allowed to access your mirror.
Please check your config.js or config.js.sample to change this.) 10.0.0.131 is my ipaddress of my Raspberry PI. I did change the default password on my Raspberry PI. I did try to change it back to the default password but got the same error message. I am also using the MMPM module to start and stop my MagicMirror, not sure if this should have any advrse effect on the Remote.

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:10.0.0.150", "::ffff:10.0.0.170"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

Please let me know what I have missed . Thank you for taking the time to read this.

Rick P.

**Comment by hriday-khurana** [comment]
You have to either specify all the range of IP Address in IPWhitelist, since your router assign the IP address dynamically or you have to leave it blank so that all ip address will be able to access your magicmirror.
ipWhitelist: []
or 
ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"]
based on your home ip address range.

**Comment by Pszoom** [comment]
Thanks for replying. Got it working.

Richard C. Pszenny
