### ISSUE TITLE
remote control automation

### ISSUE THREAD

**Issue by joelplambeck** [Jopyth/MMM-Remote-Control#21]
Hi, what an awesome module!

I'd like to automate the monitor to be turned on when my phone connects with my home wlan and have the monitor turned off if I'm no longer connected to my home wlan, in order to reduce energy costs of the monitor. 
I tried to find something with IFTTT but I struggle with open the link of your remote acces in the local network as it only works in it.

I hope you understand what I try to do and would extremely appreciate any help on this!
Thank you very much!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
