### ISSUE TITLE
As soon as I put the module into the config the config breaks

### ISSUE THREAD

**Issue by lyonrt** [Jopyth/MMM-Remote-Control#210]
Hello,  I tried to do both the auto and manual install on my Pi and as soon as I get to the step to insert the module into the config, the config breaks.

{
    module: 'MMM-Remote-Control'
    // uncomment the following line to show the URL of the remote control on the mirror
    // , position: 'bottom_left'
    // you can hide this module afterwards from the remote control itself
    config: {
        customCommand: {},  // Optional, See "Using Custom Commands" below
        customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
        showModuleApiMenu: true, // Optional, Enable the Module Controls menu
        apiKey: "",         // Optional, See API/README.md for details
    }
},

I payed attention to the comma and was sure the brackets and commas line up.  What can we do to troubleshoot?

**Comment by ezeholz** [comment]
Hey! So, this module isn't maintained anymore. However, that change is something we know, and is already into PR.

You can look up into my fork, that have some changes and improvement from the real code. 

I encourage you to close this issue if I already answered you, so people find their own issues in a quicker way. 

Cheers :D

**Comment by lyonrt** [comment]
Thx.  How would I modify the install to include your fork?  I can't find
your git clone address.

Thx,

Tyler

**Comment by BLoodConstructions** [comment]
Anyway, there's is a missing comma after 

position: 'bottom_left'

That should work.

**Comment by ezeholz** [comment]
> Anyway, there's is a missing comma after
> 
> position: 'bottom_left'
> 
> That should work.

Yep, that's the PR I'm talking about. #149
