### ISSUE TITLE
Modules not showing up

### ISSUE THREAD

**Issue by lukepetrula** [Jopyth/MMM-Remote-Control#213]
I got the remote to work just fine, but when changing the hostname and whitelisting IPs it seems that none of my other modules will show up. So I’m going to have to do without the remote for a bit until I figure out why it’s not letting any of my other modules come up. Appreciate any help I can get.

**Comment by lukepetrula** [comment]
> I got the remote to work just fine, but when changing the hostname and whitelisting IPs it seems that none of my other modules will show up. So I’m going to have to do without the remote for a bit until I figure out why it’s not letting any of my other modules come up. Appreciate any help I can get.

I should also add that the remote works, turns the monitor on and off and all that, when I view the mirror from my phone all of the modules are there, but when I look at the mirror I have a black screen.

**Comment by ezeholz** [comment]
Try refreshing the browser, with Remote Control and also F5. Is there any error in console? Pressing ctrl + alt+ i and going to the console tab.

**Comment by elustig115** [comment]
@lukepetrula  I am not sure how to help with your problem, but I was wondering if you did anything different than the ReadMe for getting connected to the website? I followed it, put my IP addresses in and still can't access it from my computer or phone browser.

**Comment by ezeholz** [comment]
@elustig115  Did you added your phone and computer IP into the whitelist config file? The "your-ip-address" text it's hardcoded, that means that the text it's not going to change despite you changing your IP.

**Comment by elustig115** [comment]
@ezeholz I had them added but just got it to work by taking out the `191.168` out of the url.
