### ISSUE TITLE
Custom Menu Notification

### ISSUE THREAD

**Issue by akashvshroff** [Jopyth/MMM-Remote-Control#214]
Hey, 

I am trying to add a custom menu and have followed all the instructions in the readme as per the location and the JSON format. In order to be able to link the remote control to MMM-pages, I am trying to send a "PAGE_CHANGED" notification with an integer (0-based page number) payload and it is not showing on my smartphone browser. The example JSON is displayed. The following is my menu:
```json
{
   "id": "custom",
   "type": "menu",
   "icon": "id-card-o",
   "text": "Change page",
   "items": [{
         "id": "custom-item-1",
         "type": "item",
         "icon": "dot-circle-o",
         "text": "Home screen",
         "action": "NOTIFICATION",
         "content": {
            "notification": "PAGE_CHANGED",
            "payload": 0
         }
      },
      {
         "id": "custom-item-2",
         "type": "item",
         "icon": "dot-circle-o",
         "text": "Photo library",
         "action": "NOTIFICATION",
         "content": {
            "notification": "PAGE_CHANGED",
            "payload": 1
         }
      },
      {
         "id": "custom-item-3",
         "type": "item",
         "icon": "dot-circle-o",
         "text": "YouTube cast",
         "action": "NOTIFICATION",
         "content": {
            "notification": "PAGE_CHANGED",
            "payload": 2
         }
      },
   ]
}
```
My custom menu does not appear on the browser.

**Comment by ezeholz** [comment]
Hey! So, I assume you follow the explain on the Readme thing. Did you move the file into your config folder? Maybe you should try to change the id of the custom menu to any other this, as that stands for and actual not repetitive id. Anyways, I'm gonna check if the code it's prepared to receive a custom menu, and gonna reach out to you if you still in the need of help.

**Comment by akashvshroff** [comment]
Hey! Yep, the file is positioned correctly - the example menu shows up in my phone but this doesn't - I suspect it has something to do with the notification and the payload? I'll try setting the id and let you know how that goes! Thanks.

**Comment by akashvshroff** [comment]
Changing the id didn't do anything! Thanks.

**Comment by ezeholz** [comment]
Okay! I think I found it. Checking out you json file, there is one comma at the end that could possibly ends in trouble. I'll let you the [page](https://jsonformatter.curiousconcept.com/) I used for you to check out both codes and see if there's an error in there. Anyways, the comma you have to erase is right after custom item 3. Let me know if that solves the issue. ;D

**Comment by akashvshroff** [comment]
This is what I got on running pm2 logs mm, there seems to be a JSON error but my JSON document seems to be okay (at least to my eyes) - 
```json
0|mm  | [2020-10-07 21:27:55.713] [ERROR]  
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [2020-10-07 21:27:55.714] [ERROR]  SyntaxError: Unexpected token } in JSON at position 363
0|mm  |     at JSON.parse (<anonymous>)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:964:83
0|mm  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
0|mm  | [2020-10-07 21:27:55.714] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [2020-10-07 21:27:55.715] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

**Comment by akashvshroff** [comment]
Let me try that!

**Comment by akashvshroff** [comment]
The menu is now showing on my phone thank you!
