### ISSUE TITLE
How do I hide the IP/URL for the MMM-Remote-Control on my magic mirror?

### ISSUE THREAD

**Issue by astan2020** [Jopyth/MMM-Remote-Control#216]
Hi all. I am very new to ANYTHING coding and am working on a magic mirror as a gift. I installed the MMM-Remote-Control module and worked through getting it added to my array of modules. I have also successfully accessed it from another computer. However, I would like to remove the url from the magic mirror display. How do I go about doing this?

**Comment by ezeholz** [comment]
Hey! According to MM2 Docs, you have to comment the position line of Control Remote into your config file. Cheers!

**Comment by astan2020** [comment]
Thanks for responding! However, I have no idea what that means.

**Comment by ezeholz** [comment]
Do you know about the MagicMirror config file? The one that have every module declared? You have to look to the Control Remote module config, and the line that says `position: down-below` or something like that, have to be `//position: down-below`

**Comment by BLoodConstructions** [comment]
Just leave position blank like
`position: "" `

**Comment by astan2020** [comment]
> 
> 
> Just leave position blank like
> `position: "" `

I tried doing that, but it messed up several of my modules. However, @ezeholz solution worked. Thanks!

**Comment by astan2020** [comment]
> 
> 
> Do you know about the MagicMirror config file? The one that have every module declared? You have to look to the Control Remote module config, and the line that says `position: down-below` or something like that, have to be `//position: down-below`

This solution worked. Thanks!

**Comment by ezeholz** [comment]
You can close the issue now! Glad to help. If you need something else, just ask. :D
