### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by goldyfruit** [Jopyth/MMM-Remote-Control#217]
Hi @Jopyth,

First of all, thanks for this module and the hard work :+1: 

I would like to know if the project still maintained?
I'm not speaking about new features but just about stability, security and updates/requirements following the MagicMirror project.

So far I see **82** issues and **12** PR and I'm wondering if the project is down _(1 year and 8 months since the last commit)_, if yes maybe it could be nice to have new maintainer(s).

Don't get me wrong, I know how hard it is to maintain open source projects but `MMM-Remote-Control` is one of the top plugins for MagicMirror!

**Comment by ezeholz** [comment]
I totally agree with you. So far I've been answering every issue that I can, and the project is stuck in this situation that nobody really knows what's going on with him. I saw a few months back that he maintain some others repos, so It's probably lack of time what's leaving this project behind. I hope someday he realize how famous this project is, and start adding maintainers to help him if he's too busy.

**Comment by goldyfruit** [comment]
> So far I've been answering every issue that I can
Wow, thanks for this!

> I saw a few months back that he maintain some others repos, so It's probably lack of time what's leaving this project behind.
Yeah life happens :)

> I hope someday he realize how famous this project is, and start adding maintainers to help him if he's too busy.
That would be great.

**Comment by goldyfruit** [comment]
@ezeholz your fork is 21 commits ahead this repository, I'm using your's and worked without any trouble.
https://github.com/ezeholz/MMM-Remote-Control

**Comment by ezeholz** [comment]
@goldyfruit Yes! I merge every issue and PR, and I'm trying to keep it updated. Every time there's an error, I recommend download the fork, just to be sure that's a completely new issue. I'm glad you like it. ;D

**Comment by Jopyth** [comment]
@ezeholz You got mail.

**Comment by ezeholz** [comment]
I'm happy to announce that I'm gonna maintain this repo for now on. Thanks a lot to Jopyth for passing by, and good luck with everything! ;D

**Comment by goldyfruit** [comment]
> I'm happy to announce that I'm gonna maintain this repo for now on. Thanks a lot to Jopyth for passing by, and good luck with everything! ;D

This is a great news! Thanks @Jopyth :+1:
