### ISSUE TITLE
Status of the monitor via rest?

### ISSUE THREAD

**Issue by dakipro** [Jopyth/MMM-Remote-Control#22]
First of all, excellent module, just what I was looking for. 
A question, is it possible to return the state of the monitor?
MODULE_DATA returns brightness of the monitor, but it doesn't say if it is on or off. Is that possible to detect and report back?
Thanks!

**Comment by Jopyth** [comment]
I am not sure if this is possible, but I will look into it. The brightness is technically not the brightness of the monitor, but the brightness of the website displayed.

**Comment by Jopyth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Monitor Status](https://trello.com/c/lY1isjDD/28-monitor-status)

**Comment by nixmeer** [comment]
Anything happened here? 

I am trying to include the mirror as an Light Bulb into HomeKit via Homebridge. would be nice if the status was returned as 0 or 1 on MONITORON, MONITOROFF and something like MONITORSTATUS

Best
jan

**Comment by shbatm** [comment]
Included in https://github.com/Jopyth/MMM-Remote-Control/pull/104 -- 
[GET /api/monitor/status](https://documenter.getpostman.com/view/6167403/Rzfni66c#0637dbba-4bc8-4854-9655-c07db5d5f418) returns an object with `monitor: on` or `monitor: off`
