### ISSUE TITLE
/monitor/off turns it off, /monitor/on brings black screen

### ISSUE THREAD

**Issue by openPhiL** [Jopyth/MMM-Remote-Control#227]
Hi. Working on a Raspberry PI 4 with a Dell Monitor hooked up via HDMI. 
Fresh installation (probably up2date), use master, and I use PM2. 
I can do monitor/off, monitor goes black and turns to standby. perfect. 
then I do monitor/on, the monitor awakes from standby - but the screen remains black. cannot get anything to the screen, not even with mouse/keyboard attached while hammering on those. need to sudo restart to get some non-black pixels back. 

Any Idea where I can look ? I don't know where to begin. 
Thanks!

**Comment by ezeholz** [comment]
Hey! Do you have an idea if it's anything from your monitor? Any errors in console? You could use `pm2 logs mm` to see the logs.

Minimizing the MagicMirror doesn't do anything, right? Just to check.

Maybe you should use another way to turn on and off your monitor, since I believe there are some problems with the default ones and HDMI.

**Comment by openPhiL** [comment]
I cannot think of anything related to the monitor as I don't see anything, just black. And restarting the PI does bring pixels back to the screen.  

I have now looked at 'pm2 logs mm' but cannot see anything unusual.
![image](https://user-images.githubusercontent.com/43743230/98674175-b83c8400-2358-11eb-8a5d-5f499b495c84.png)

I probably could turn off/on with disconnecting the power from the monitor or so, that is my fall-back option - I don't have my final mirror display yet to be sure. 

Any other ideas where to look into? I hate beeing the only one with a problem, so you can close the issue if that is the case and I blame my Dell monitor.

**Comment by ezeholz** [comment]
As stated in #38
> Change the command to:
> vcgencmd display_power 0 (For off)
> vcgencmd display_power 1 (For on)
> 
> This will keep the screen buffer state alive. While tv service forgets the screen buffer state hence MONITORON appears to fail 
> 
> Issue with using tvservice: (From Raspberry Pi Documentation)
> 
> Important Note: Powering off the output using this command will also destroy any framebuffers/dispmanx layers associated with the display. These are NOT re-established with a subsequent power on, so will result in a blank screen.
> 
> A better option is to use the vcgencmd display_power option, as this will retain any framebuffers, so when the power is turned back on the display will be the returned to the previous power on state.

I think this is the problem. So I think you can use those commands plus
`vcgencmd display_power -1` as the statusMonitor.

If you're using the last version from the master branch, it's mandatory for you to use the monitor status. Next release will include a better implemented way of monitor handle.

Can you confirm me if this approach works? 
Cheers :D

**Comment by openPhiL** [comment]
Hi. I can confirm that those commands do work via ssh. 
So I added them into the node_helper.js (as from #38) . 
Using the GET requests, I was able to turn it off, but turning on brings :

    {"success":true,"monitor":"unknown"}

![image](https://user-images.githubusercontent.com/43743230/98737170-22c7e100-23a6-11eb-899a-f4406c7c55f5.png)
I tried without the && sudo chvt.. things as well. 
Switching then back to ssh and enter the command there, works. 
How should I change the node_helper.js the right way?

**Comment by openPhiL** [comment]
oh, here is the log: 
![image](https://user-images.githubusercontent.com/43743230/98737592-b13c6280-23a6-11eb-8d51-9b0ec7bcbe1d.png)

For me, it looks, that my turnOn command is sending the display_power 0... not the 1.. ?

**Comment by ezeholz** [comment]
You could try using the develop branch, I change the way the monitor turn on and off, and maybe that's why it's not turning on. Turning on your monitor via ssh works, right?

**Comment by openPhiL** [comment]
alright! now it is working. 
had to google first how to git a branch, but when I then change the node_helper.js in that branch, it works! 

![image](https://user-images.githubusercontent.com/43743230/98739355-7851bd00-23a9-11eb-8d19-9b86130f163d.png)

![image](https://user-images.githubusercontent.com/43743230/98739314-64a65680-23a9-11eb-96db-e79e1fb9a82d.png)

log is ok, monitor is actually showing pixels and the json-response is fine, too: 
![image](https://user-images.githubusercontent.com/43743230/98739769-43923580-23aa-11eb-9c86-fd985f750a2c.png)

Thank you for your help!
PhiL
PS: Am I suppose to close that or you? what is best practice? :D

**Comment by ezeholz** [comment]
Glad to help! In the next few days I'm gonna release that branch. You can use the develop until then.
Keep Programming! :D
