### ISSUE TITLE
No consideration of the module number

### ISSUE THREAD

**Issue by JVF2** [Jopyth/MMM-Remote-Control#229]
Hi guys,

if I had several modules with the same name, inserting the module number worked until now.
For example:
"http://192.XXX.XXX.XX:8080/remote?action=SHOW&module=module_10_MMM-SmartWebDisplay"

Currently, regardless of the number, all modules named "MMM-SmartWebDisplay" are shown or hidden.

What am I doing wrong?

Many thanks in advance.

**Comment by ezeholz** [comment]
Hey! Do you try using the api for that? Are you using the last version of the Remote Control?

**Comment by JVF2** [comment]
Hello,

thank you for the quick response.

What do you mean, do I use the API? Unfortunately I am not an expert. :-(
So far my homee sent the exemplary link. That worked well.

Yes, I have installed the current version.

**Comment by ezeholz** [comment]
In the last version I change a few paths, and maybe broke the remote endpoint. I'll check it. In the meantime, you should use the api, that's the new implementation of the 2.0.0
To use it, you can go to http://192.xxx.xxx.xxx:8080/api/docs
There it's every single endpoint you can use.

I believe the one you're looking it's http://192.xxx.xxx.xxx:8080/api/module/module_10_MMM-SmartWebDisplay/show

Let me know if that works. Cheers ;D

**Comment by ezeholz** [comment]
Let me know if that commit let you hide only the module you want.

**Comment by JVF2** [comment]
The commit works.
Thank you very much!

**Comment by ezeholz** [comment]
Thank you for letting me know! Fixing it in the master branch now.
