### ISSUE TITLE
Pb with update

### ISSUE THREAD

**Issue by pgille** [Jopyth/MMM-Remote-Control#231]
Hello !
First thank you for your soft.

With the last update there is a pb

I have this message 

best regards

Well that didn't work. Check the MM logs for more details:

{
   "success": false,
   "status": "error",
   "reason": "unknown",
   "info": {
      "task": {
         "commands": [
            "pull"
         ],
         "format": "utf-8"
      }
   }
}

**Comment by ezeholz** [comment]
Hey! So, as I can see, you're trying to download the update. Do you have got installed? Are you using the develop branch or the main one?

**Comment by pgille** [comment]
Hello
I use the software remote.html and i use the update menu : i don't choose anything : i leave the software doing the update

Thank you

**Comment by ezeholz** [comment]
Alright, just for you to know, the 2.2.0 broke the update menu, my fault. It's already fixed in the 2.2.1, but you'll have to clone it manually, or use the script included in the installation. Sorry for the inconvenience. Tell me if updating that way, you're not having issues with the fix I'm going to push soon. Cheers :D

**Comment by spookyannie** [comment]
How do you clone manually? i get this error when trying to clone:

![image](https://user-images.githubusercontent.com/13205114/100153195-a37fe600-2e58-11eb-86dd-a81aa7f0e105.png)

**Comment by ezeholz** [comment]
First do `git reset --hard`, and then `git pull`. That should do the trick.
If not, delete the folder and inside modules use `git clone https://github.com/jopyth/MMM-Remote-Control.git`

**Comment by spookyannie** [comment]
If not, delete the folder and inside modules use `git clone https://github.com/jopyth/MMM-Remote-Control.git`
**This work'd**

**Comment by ezeholz** [comment]
I assume this is resolved!, If not, feel free to reopen or create another issue. Cheers! :D

**Comment by pgille** [comment]
Hello
Thank you
