### ISSUE TITLE
make it easier to add custom code to module config

### ISSUE THREAD

**Issue by finius04** [Jopyth/MMM-Remote-Control#236]
Im finding it really difficult to add these lines of code to the MMM-NowPlayingOnSpotify module:
    clientID: "8f0c9d7843vdcfz23fbc",
    clientSecret: "c0eadsfasd65341da88636f9d",
    accessToken: "-Ia9BqFcKC6nrIKNxfZGifgsjvZq5tsC5XgNMnFDh7rn3QXPAU6yJF3CsZ7HHrQggw",
    refreshToken: "AQC9JqQ2gFTtqQAEslVsdfgafyPZjPOSHPZmKp1Y"

(these aren't the real details for security reasons)

It would be great if you could make it easier to adjust the config file.

Thanks :)

**Comment by ezeholz** [comment]
Hey! You're using the "Edit config.js" option in the Remote, right? Over there, you should see the module installed. Inside that option, you'll have to set the `config` tab with the values you're saying, for example:
![image](https://user-images.githubusercontent.com/30635862/102355712-fe55ba80-3f8a-11eb-829c-0c9b32247c67.png)
That way, in the config file you'll end up with:
![image](https://user-images.githubusercontent.com/30635862/102355773-14637b00-3f8b-11eb-8eb2-e68937e2ceb6.png)

**Comment by finius04** [comment]
@ezeholz Thanks for that - i've now got it working.
I was using inverted commas in the string field so that's why it didn't work.
