### ISSUE TITLE
Sending Monitor ON when monitor is already on, blanks the screen (not in powersave)

### ISSUE THREAD

**Issue by herwarth** [Jopyth/MMM-Remote-Control#240]
Hello,
The api call http://<IP>:8080/api/monitor/on puts the monitor ON.
The api call http://<IP>:8080/api/monitor/off puts the monitor OFF.
The api call http://<IP>:8080/api/monitor/status always returns {"success":true,"monitor":"on"}
Even when I put it off using the api.

When the monitor is ON and I give another api call http://<IP>:8080/api/monitor/on. It keeps the monitor ON but blanks the screen.

**Comment by ezeholz** [comment]
Hey! This issue could be because how `tvservice` works. The next update is gonna bring the `vcgencmd` command, that's a better implementation.
Could you try using the develop branch?

**Comment by ezeholz** [comment]
Hey! So I didn't get a response from you in a while, I could assume that the last release fix your issue. Feel free to re-open if you still having issues. Cheers :D
