### ISSUE TITLE
Restart MagicMirror not working

### ISSUE THREAD

**Issue by chen32g** [Jopyth/MMM-Remote-Control#244]
Hello,

The function Restart MagicMirror is not working for me.
The refresh is working.

I believe it's related to the Magic Mirror installing process.
How can I custom the Restart command to " pm2 restart MagicMirror " ?
I try in the custom command section but didn't work.

Thank you.

**Comment by ezeholz** [comment]
Whops, my bad that I forgot to add it inside the wiki.

You can use `pm2ProcessName` inside the config file to change the default `mm` value into `MagicMirror`

**Comment by chen32g** [comment]
Hi, Thank you for the update.
I try it but still not working.
I added the following command to my Config file,
pm2ProcessName: 'MagicMirror',

Please advise.
Thank you.

**Comment by chen32g** [comment]
Found the problem.
pm2 folder also need to be on "node_modules".
To do that need to run the following command in the MagicMirror folder
npm link pm2

After that all work.

Thanks!
