### ISSUE TITLE
 Installation or configuration problem?! help please

### ISSUE THREAD

**Issue by JeromeClavier** [Jopyth/MMM-Remote-Control#246]
|**MagicMirror version?**|   | last version
|**How do you install MM?**|   | Install on Raspberry Pi 3b+( with Raspberry Pi imager for Debian version) and install of MM by following the guide
|**MMM-Remote-Control version?**|   | last version
|**How do you install Remote Control?**|   | Manual install
|**Did you try using just Remote Control alone with MM?**|   | No, the remote control is not visible on the MM and I cannot access it

### Description

After following the installation and configuring "config.js", I cannot access the remote control, whether from the Pi, from my computer or from my phone despite being on the same Local network.
When I type ip-local-de-mon-Pi: 8080 / remote.html, it tells me "
This device is not authorized to access your mirror.
Please check your config.js or config.js.sample to change this. "
I have checked but I find no error.
I passed "address to 0.0.0.0" and ipwhitelist where I added an ipv4 range to be able to access it from my phone or my computer but I admit having trouble understanding what I did wrong (I am brand new in this world).
I attach the config of the beginning and the part concerning MM-remote-control.

i'm sorry for the syntax, i'm french, i used google translate and this is my first on github.
Thank you

### config.js

var config = {
        address: "0.0.0.0",     // Address to listen on, can be:
                                                        // - "localhost", "127.0.0.1", "::1" to listen on loopba$
                                                        // - another specific IPv4/6 to listen on a specific int$
                                                        // - "0.0.0.0", "::" to listen on any interface
                                                        // Default, when address config is left out or empty, is$
        port: 8080,
        basePath: "/",  // The URL path where MagicMirror is hosted. If you are using a Reverse proxy
                                        // you must set the sub path here. basePath must end with a /
        ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.*.*/24"], 
************************************************************************************************************
{
                        module : 'MMM-Remote-Control' ,
                        // décommentez la ligne suivante pour afficher l'URL de la télécommande sur le miroir
                        // position: 'bottom_left',
                        // vous pouvez ensuite masquer ce module depuis la télécommande elle-même
                        config : {
                                customCommand : { } ,   // Facultatif, Voir «Utilisation des commandes personnal$
                                showModuleApiMenu : true ,  // Facultatif, Activez le menu Contrôles du module
                                secureEndpoints : true ,  // Facultatif, Voir API / README.md
                                // décommentez l'un des les lignes ci-dessous si vous comptez l'utiliser
                                // customMenu: "custom_menu.json", // Facultatif, Voir "Éléments de menu personn$
                                // apiKey: "", // Facultatif, Voir API / README.md pour plus de détails
                                // classes: {} // Facultatif, Voir "Classes personnalisées" ci-dessous
                                 }
                },

**Comment by ezeholz** [comment]
You're doing everything right, but need to specify better the ipWhitelist. I recommend using `["127.0.0.1","::ffff:127.0.0.1","::1","192.168.0.1/24","::ffff:192.168.0.1/120"]`

First you need to know for sure you ip subnet. You can do that in every mobile, going inside configuration and seeing your ip number. If it's 192.168.0.***, it's totally fine. If it's 192.168.1.*** or something like that, you'll need to change it accordingly.

I'll let you a [website](https://forum.magicmirror.builders/topic/1326/ipwhitelist-howto/2) from MM were they explain in detail how does this work. Anyways, I'm here if you need anything else. Cheers :D

**Comment by JeromeClavier** [comment]
Hello and thank you for your answer.
If I do everything correctly, it's already good !!
I looked before doing it and when config the whitelist I put 192.168.1. 1/24
At first I tried entering the IP address of my phone and my computer directly, but it was the same.
Should I open the redirect ports on my box. (exactly, it's a 4G LTE TP Link router with a Bouygues Télécom chip)
The router does not change anything since it is local !?
I went to see yours link, no command works for me!
I typed in the terminal "pm2 log" and here are the logs
Thanks again!!
![Log1](https://user-images.githubusercontent.com/77678878/105204860-dd155a80-5b44-11eb-8e60-e1893717cb03.jpg)
![Log2](https://user-images.githubusercontent.com/77678878/105204735-c969f400-5b44-11eb-858c-4357730d0548.jpg)

**Comment by ezeholz** [comment]
Hey! If you're using it locally, I believe there's no need to open ports. Try using to copy and paste the following.
`["127.0.0.1","::ffff:127.0.0.1","::1","192.168.1.1/24","::ffff:192.168.1.1/120"]`

If that doesn't work, try to open it to all of the IPs, for that you should use `[]`

**Comment by JeromeClavier** [comment]
Hi Eyholz!!
I'm glad you answered ...
This is what I thought for the router ports but in doubt I tried to open some but it didn't work either.
So, I copied your IP list and relaunched it with your command and ...... it works (with the pc or the phone !!!!!!!!
Many thanks !!!!!!
I compared between our IP lists and yours, there is just ":: ffff:" less and it's good ... why?
You said if the list didn't work I could use [] .... How?
replace the whole list with [] or in addition to IP?
And to use it from outside, outside the local network, how does it work?
Another big thank you to you, it's really cool !! Like this module!
 Well done and thank you to the Dev !!!!!!

**Comment by ezeholz** [comment]
Glad to know that's working! The ::ffff part is for IPv6, and most of the devices that we use normally doesn't have them.

If you want to use it externally, you'll have to make your IP static and then open ports and add it just like your phone or your computer IP. It's a more complex process and it's not entirely necessary.

I'm gonna close this issue as resolved, if you feel that you need more help, please reopen this one or create a new one. Cheers :D
