### ISSUE TITLE
timout error 

### ISSUE THREAD

**Issue by antoinegv7** [Jopyth/MMM-Remote-Control#247]
i've configured my module without any problems, i've added: address: "0.0.0.0", and ipWhitelist: [], so as not to have any problem with the connection, and when putting https://xxx.xxx.x.xx:8080/remote.html (with my ip of course) i have either connection refused or timout error.

## I have a problem

|Questions||
|---|---|
|**MagicMirror version?**|   |
|**How do you install MM?**|   |
|**MMM-Remote-Control version?**|   |
|**How do you install Remote Control?**|   |
|**Did you try using just Remote Control alone with MM?**|   |
|**If you did, were you able to reproduce the bug?**|   |

### Log

```text
Paste the log you're getting, and possibly the error, over here.

Please, be sure that none of your personal information, such as IP or passwords are exposed.
```

### config.js

```js
/* Paste here your config.js file.

Make sure that none of your personal data is present, specially check for:
- IPs from MM instance, or the ones that are whitelisted. Please, replace them with *** so we're totally sure that you have set them.
- API keys, Tokens from different modules, URL to private calendars.
- Directions or Personal data. */
```

**Comment by ezeholz** [comment]
The router might be blocking you, if you insolate the devices, you won't be able to access. Try using localhost.

MM should show a message when it's blocking you, that's not up to Remote Control.

Please stick to the template for issues. Thanks
