### ISSUE TITLE
Add your own command

### ISSUE THREAD

**Issue by jamie0911** [Jopyth/MMM-Remote-Control#248]
Hi,Please please can someone help me i have tried to add my own command menu to the menu section to turn on and off modules but it isnt showing.The config file is working but i dont know what to do please help me

**Comment by ezeholz** [comment]
Please check out the [Wiki](https://github.com/Jopyth/MMM-Remote-Control/wiki/Custom-Menus) to understand better your problem.

This is not a bug, it's a question, and it's not even with the according template, please use available templates.
