### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jamie0911** [Jopyth/MMM-Remote-Control#249]
Hi i recently posted and that got closed i have been on here can someone dumbing it down just because i am not that good at code please can you help and will u need my config file?

**Comment by ezeholz** [comment]
What's the trouble? You still not using the appropriate template format. They're there for a reason. Please use them.

**Comment by jamie0911** [comment]
I have.Im sorry im only a kid trying so hard i have been trying so hard but it wont work

**Comment by ezeholz** [comment]
If everything is installed correctly, you should enter your MagicMirror IP, like this 192.168.0.1:8080/remote.html

The exact url for you it's showed when you set a position to the Remote Control in your config file.

Over there, you should have a nice menu where you can do pretty much anything you can. Doesn't need too much of coding to get it up and running.
![image](https://user-images.githubusercontent.com/30635862/106135197-595ffd00-6146-11eb-8db3-7bc78921010c.png)

**Comment by jamie0911** [comment]
I have that installed so i can controll it from the menu but how do i add my own commands?
![image](https://user-images.githubusercontent.com/78140263/106135709-30e4fc80-6160-11eb-83e1-3149dc2fcc37.png)

**Comment by ezeholz** [comment]
Using Custom Commands, you can see them over here: https://github.com/Jopyth/MMM-Remote-Control/wiki/Custom-Commands

Anyways, If you wanna hide or show modules, maybe you don't need custom commands at all. using the `Edit View` menu can do that. If you want to set multiple modules to show and hide at the same time, use Classes over here: https://github.com/Jopyth/MMM-Remote-Control/wiki/Classes

**Comment by jamie0911** [comment]
Do i just add config: {
    classes: {
        "Any Name You Want": {
            hide: ["calendar"],
            show: ["newsfeed"],
            toggle: ["clock"],
        },
        "Another Name You Want": {
            hide: ["newsfeed"],
            show: ["calendar"],
        },
    },
}, 
to my config file

**Comment by ezeholz** [comment]
Inside the Remote Control module, yes.

Should be something like this:
```
{
    module: 'MMM-Remote-Control',
    position: 'bottom_left',
    config: {
        classes: {
            "name": {
                toggle: ["clock"]
            }
        }
    }
},
```

With whatever you want to do

**Comment by jamie0911** [comment]
How do I add several ones could u send me the config for that please?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ezeholz** [comment]
{
    module: 'MMM-Remote-Control',
    position: 'bottom_left',
    config: {
        classes: {
            "name": {
                toggle: ["clock"]
            },
           "name2": {
                toggle: ["clock"]
            },
           "name3": {
                toggle: ["clock"]
            },
        }
    }
},

**Comment by ezeholz** [comment]
Seems to be resolved, please reopen it if you need more help. Cheers :D
