### ISSUE TITLE
Some modules can not be hidden

### ISSUE THREAD

**Issue by Burner911** [Jopyth/MMM-Remote-Control#25]
I notice that I can only hide the clock and calendar by default using the menu of the remote. When I attempt to hide any other module the toggle switches to hidden, but the module remains on the mirror.

**Comment by Jopyth** [comment]
Interesting. Will look into this.

**Comment by KilianB** [comment]
Might be related to #26

**Comment by Jopyth** [comment]
Is it then also possibly fixed by my changes on the `develop` branch?

**Comment by Jopyth** [comment]
Closing this issue for now, feel free to reopen if the bug still exists in the last version.
