### ISSUE TITLE
When I start my magic mirror it doesn't show anything after setting the code on the config files can you help?

### ISSUE THREAD

**Issue by IceGhosting** [Jopyth/MMM-Remote-Control#250]
## I have a problem

|Questions||
|---|---|
|**MagicMirror version?**|   |
|**How do you install MM?**|   |
|**MMM-Remote-Control version?**|   |
|**How do you install Remote Control?**|   |
|**Did you try using just Remote Control alone with MM?**|   |
|**If you did, were you able to reproduce the bug?**|   |

### Log

```text
Paste the log you're getting, and possibly the error, over here.

Please, be sure that none of your personal information, such as IP or passwords are exposed.
```

### config.js

```js
/* Paste here your config.js file.

Make sure that none of your personal data is present, specially check for:
- IPs from MM instance, or the ones that are whitelisted. Please, replace them with *** so we're totally sure that you have set them.
- API keys, Tokens from different modules, URL to private calendars.
- Directions or Personal data. */
```

**Comment by ezeholz** [comment]
You doesn't fill anything inside the template, there's little I can do.
Please complete the template and re-open if you still having this issue.
