### ISSUE TITLE
How to PAUSE page rotation on MMM-Pages ?

### ISSUE THREAD

**Issue by maxencekyz** [Jopyth/MMM-Remote-Control#255]
Hello to the community and developers @Jopyth @goldyfruit @MonkoftheFunk @qistoph ,

Thanks for the module, i have so many modules and they are all working fine ! Well done guys :)
Now, I would like to be able to pause the rotation of MMM-Pages with MMM-Remote-Control
I searched and tried many things but not successful at all ...

Any tutorial on how to implement the notification "PAUSE_ROTATION" and implement it in the remote control here ?
Or just be able to have a button anywhere in the menu to PAUSE/RESUME rotation ?

![Capture](https://user-images.githubusercontent.com/80335419/112508808-2c1f7c00-8d90-11eb-960e-66a57abd4ae4.JPG)

Thanks a lot for your help !
I love this community

**Comment by ezeholz** [comment]
Hey! Welcome :D

Personally I don't use that specific module, but there should be a way to add a button somewhere.

I believe that you're using the module control from the main menu. That particular menu is created mostly by guessing and could not be accurate. You can read more about this over [here](https://github.com/Jopyth/MMM-Remote-Control/wiki/API#methods)

If MMM-Pages use the pause notification, then you could call it using the [notification API](https://ezeholz.com.ar/MMM-Remote-Control/#/Module%20Control/get_api_notification___notification_____p_) or [Custom Menus](https://github.com/Jopyth/MMM-Remote-Control/wiki/Custom-Menus).

Let me know if you need anything else
Cheers :D

**Comment by maxencekyz** [comment]
Hello @ezeholz 

Very clear ! Appreciate your help, thanks a lot 
Have a wonderful day mate <3
