### ISSUE TITLE
(deprecated) request package missing in package.json

### ISSUE THREAD

**Issue by khassel** [Jopyth/MMM-Remote-Control#257]
The `request` package used [here](https://github.com/Jopyth/MMM-Remote-Control/blob/2daec303f5ddea8288daedfa2941dc9e9bba4d8b/scripts/download_modules.js#L15) is deprecated.

See [npm repo](https://www.npmjs.com/package/request).

Today we removed the last runtime dependency using `request` in the MagicMirror project so if you install the current `develop` branch of MagicMirror without devDependencies this module will not work anymore, because `request` is missing in your `package.json`.

2 options:
- add `request` to your `package.json` or
- replace `request` e.g. with `node-fetch`

I would prefer the second solution.

Thanks,

Karsten.

**Comment by ezeholz** [comment]
Thanks for the heads up, I'm gonna hotfix that ASAP. ;D
