### ISSUE TITLE
Module will break if modules are hidden by default 

### ISSUE THREAD

**Issue by KilianB** [Jopyth/MMM-Remote-Control#26]
See issue filed over at the main repository https://github.com/MichMich/MagicMirror/issues/664.

No undefined check is present thus the module will fail and lead to non expected behavior like not being able to hide apps following deeper down in the config file.

`if (modules[i].identifier === moduleData[k].identifier) {`
https://github.com/Jopyth/MMM-Remote-Control/blame/master/MMM-Remote-Control.js#L76

**Comment by Jopyth** [comment]
This should be fixed on the `develop` branch. Can you confirm this?

**Comment by KilianB** [comment]
I'll be able to test this in a few hours
