### ISSUE TITLE
Not able to connect via the browser

### ISSUE THREAD

**Issue by osastar** [Jopyth/MMM-Remote-Control#260]
Hello all,

I've followed the steps and installed the Remote Control but i'm left with a problem.

Yesterday, I was able to go on the remote control interface but now it just doesn't work. I haven't changed anything. When i surf to the IP:8080/remote.html it says that the page isn't available.

i've set the address to 0.0.0.0 and left the IPwhitelist Empty  []. Can someone please help me? this is for a school project :) thanks in advance

**Comment by osastar** [comment]
I just found out that it only works when i'm using a wired connection on my laptop, On wifi it still doesn't work

**Comment by ezeholz** [comment]
Hey! Did you check the IP of the mirror? Maybe it changed, and now you're trying to access to an unknown PC.
Can you access in your mirror itself using localhost? The console shows anything or just normal log?

**Comment by osastar** [comment]
The IP of the mirror is still the same. I just found out that it only works when i'm using a wired connection on my laptop, On wifi it still doesn't work

**Comment by ezeholz** [comment]
You're running it in a RPi or another OS?

**Comment by osastar** [comment]
RPi

**Comment by osastar** [comment]
i also can't access the UI website through my phone, only a wired connection is able to surf on the website

**Comment by ezeholz** [comment]
You could try opening ports of your router, that's probably causing the issue.

**Comment by osastar** [comment]
the 8080 port?

**Comment by ezeholz** [comment]
Yep, that's the one by default. If you are unable to access the Remote Control, it'll show a warning message. If you're not seeing anything like that, it's probably because you can't even reach the mirror.

**Comment by osastar** [comment]
i should open it specifically for the ip of the Pi right?

**Comment by ezeholz** [comment]
You said that only wired connections can access the mirror, right? Routers sometimes have an isolation option, I don't remember if it's just for wifi or also for wired. But check the router's settings and disable that option if you have it.

**Comment by websterjazz** [comment]
I am facing the same issue... I tried all the above solutions.. Nothing seems to work... Anything that I ma missing here?

**Comment by ezeholz** [comment]
@websterjazz Can you access via eth but not via wifi, right? Did you reload MM when doing those changes? Is there anything showing up in the log?

**Comment by ezeholz** [comment]
Glad to help!
I'm gonna close this issue now, but feel free to open another one.
Cheers!
