### ISSUE TITLE
Rest API response onls success message

### ISSUE THREAD

**Issue by andia89** [Jopyth/MMM-Remote-Control#261]
When I run 

`curl --location --request GET 'http://localhost:8082/remote?action=MODULE_DATA' --data-raw ''` (yes my port is 8082)

the response I get is: 

`{"success":true}` and nothing else. I am confused because it should list all the modules installed as far as I understand. Is there a way to debug that?

**Comment by ezeholz** [comment]
Hey! Try with `http://localhost:8082/api/module` instead.
Also, you can see docs by using `http://localhost:8082/api/docs`

Let me know if that helps you! :D

**Comment by ezeholz** [comment]
Hey! Try with `http://localhost:8082/api/module` instead.
Also, you can see docs by using `http://localhost:8082/api/docs`

Let me know if that helps you! :D

**Comment by andia89** [comment]
Unfortunately not
`http://localhost:8082/api/docs` -> this works 
`http://localhost:8082/api/module` -> this results in 
`"success":false,"status":"error","reason":"unknown","info":"Not initialized, have you opened or refreshed your browser since the last time you started MagicMirror?"` even though I did nothing of this kind

**Comment by ezeholz** [comment]
Even if you restart the mirror, the message still showing?
Is there any error in console?

Which modules do you have? Did you try using just MM and RC module alone?

**Comment by andia89** [comment]
Oh yes that was it. For some very weird reason I don't fully get your module doesn't work with this one 
https://github.com/shaneapowell/MMM-GmailFeed

Thanks

**Comment by ezeholz** [comment]
Thanks for letting me know!
I'll try to fix compatibility with other modules ASAP.
Cheers :D
