### ISSUE TITLE
Blackscreen with v2.3.6

### ISSUE THREAD

**Issue by SirLocke** [Jopyth/MMM-Remote-Control#265]
I get a Blackscreen with v2.3.6. - I tried reinstalling the module, but it didn't help. 
2.3.5 works fine for me. 

Error was something like 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /home/pi/magicMirror/MagicMirror/node_modules/uuid/package.json

in mm Logs

**Comment by ezeholz** [comment]
I'm so sorry to hear that.
It's strange because there weren't a major change in the code, so it should work.
I'll check the code and get back to you ASAP.
In the meantime, you could try getting back to the previous version, so you are able to use the Mirror.
Cheers!

**Comment by ezeholz** [comment]
Let me know if the branch `bug-fixes` works for you. :D

**Comment by SirLocke** [comment]
I did use   "uuid": "^3.3.2" 
v2.3.6 works for me so updating the module list did the trick? 
Thank you!

**Comment by ezeholz** [comment]
That error just come across if UUID is on the last version, 8.x
That's why it was strange. Glad you were able to fix it! :D
