### ISSUE TITLE
Should config.js be rewritten by the MMM-Remote-Control module?

### ISSUE THREAD

**Issue by Dimasua** [Jopyth/MMM-Remote-Control#266]
Hej, I'm using the module for a while, which is a really great addendum, but just noticed that my config.js file is overwritten by Remote Control Module. At least that line appeared on top of the config.js file like that: ******* AUTO GENERATED BY REMOTE CONTROL MODULE *******
The original upper part of the module now looks different and there are no parameters that were before.

Can you please clarify if that is expected behavior and why the module overwrites the config.js file?

Thank you in advance!

**Comment by ezeholz** [comment]
Hey! So, the header you're seeing it's because RC received a request to generate that file, either you with the menu or any module send the request to change something inside the `config.js`.
Also, that's why RC creates a backup file. That file contains the exact configuration that's being overwritten.

What parameters are not being shown?

**Comment by Dimasua** [comment]
I didn't find the following parameters:

language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",

**Comment by ezeholz** [comment]
All those seems to be the default values. RC takes them out because they're redundant, that also happens with the default configuration of modules.

**Comment by Dimasua** [comment]
Ok, is there a way I can change those parameters if they are out? For example having 12h time format?

**Comment by ezeholz** [comment]
If you set something not-default like `time format: 12` then yeah, it should stay in the config file
