### ISSUE TITLE
Disable Update Notifications

### ISSUE THREAD

**Issue by loki131** [Jopyth/MMM-Remote-Control#269]
### Description

It would be nice to be able to Disable Update Notifications. Either a switch to turn them off in the remote or an option in the config to permanently disable. 

I have a module that needed to be updated manually (I assume because it's not on the 3rd Party Modules page) and the mirror was getting spammed with update messages! Not a huge deal but I wasn't available to do the update for about a week and I was informed the only way to get rid of the messages and actually see what's happening on the mirror was to launch the MagicMirror on the remote and dismiss them individually and that I'm the worst for not getting this updated in a timely manner! 

Incase you are wondering I'm using the [MMM-NewPIR](https://github.com/bugsounet/MMM-NewPIR) module which was the only PIR module I was able to get working the way I wanted!

Thanks!

**Comment by ezeholz** [comment]
Which notification are you pointing out? I believe that you can take the one displayed in the mirror by just removing the `updatenotification` module. Are you talking about that?

**Comment by loki131** [comment]
Of course I actually updated the module so the messages are gone... but I did write down what they were!

Update for MMM-NewPIR module
[NPM] @bugsounet/npmcheck v09.9.95 -> v0.9.96

Update for MMM-NewPIR module
[NPM] @bugsounet/screen v1.1.8 -> v1.1.8

I guess I assumed they were coming from your module but I'm new to this so it's very possible that I'm wrong!

**Comment by ezeholz** [comment]
Don't worry! Thank you so much for letting me know the versions. I'll check if there's something I can do, and get back to this issue.

PD: I'm mostly sure that RC grab the info from the `.git` folder, so I assume that deleting that folder should do the trick. :D

**Comment by ezeholz** [comment]
Hey! That could be something related to the `updatenotification` default module. I'll let you a link [here](https://docs.magicmirror.builders/modules/updatenotification.html) with instructions on how to configure it. Try ignoring the module you're getting an update.

**Comment by ezeholz** [comment]
So I checked the code of NewPIR and you're correct, that module sends a notification when a new version is available. You should create a issue over there to let them know your thoughts.

About the MM update. If you don't have it updated, most probably it's because it wasn't downloaded using git. That's a limitation I cannot handle with the Remote Control right now. Even it applies to every other module, actually.

Let me know if you have any other question, and I'll be glad to answer them!

**Comment by ezeholz** [comment]
If you used `git clone`, then you're just fine. You'll have the update when they release it.
