### ISSUE TITLE
Error pop-up msg when using "Restart MagicMirror"

### ISSUE THREAD

**Issue by Coolie1101** [Jopyth/MMM-Remote-Control#272]
### OS

OS: "Raspbian 10 (buster)"

### NodeJS Version

NodeJS: 14.18.1

### MagicMirror Version

MM: 2.17.1

### Remote Control Version

Remote Control: 2.3.6

### Did you try using just Remote Control alone with MM?

- [X] I have and the error still happening

### Description

I get the following pop-up message in the web browser when executing "Restart MagicMirror", but the function executes and MM restarts.

![image](https://user-images.githubusercontent.com/28989417/142620485-f0142835-9ec2-45bc-98ae-ac62319f8d59.png)

### Expected behavior

I would think a success message or some sort of confirmation that the command was successful. 

### Current behavior

Error message pop-up.

### Steps to reproduce

1. Start MM
2. Wait until everything loads
3. Click "Restart MagicMirror"
4. Get error message pop-up after a few seconds.

### Log

```shell
N/A
```

### config.js

```javascript
/* Magic Mirror Config Sample
*
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/getting-started/configuration.html#general
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "0.0.0.0", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	electronOptions: {
		webPreferences: {
		webviewTag: true
		}
	},
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: ['127.0.0.1','localhost','192.168.200.0/24'], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "imperial",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: 'MMM-Remote-Control',
			// uncomment the following line to show the URL of the remote control on the mirror
			// position: 'bottom_left',
			// you can hide this module afterwards from the remote control itself
			config: {
				customCommand: {},  // Optional, See "Using Custom Commands" below
				showModuleApiMenu: true, // Optional, Enable the Module Controls menu
				secureEndpoints: true, // Optional, See API/README.md
				// uncomment any of the lines below if you're gonna use it
				// customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
				apiKey: "********************", // Optional, See API/README.md for details
				// classes: {} // Optional, See "Custom Classes" below
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Comment by OberfragGER** [comment]
> ### OS
> OS: "Raspbian 10 (buster)"
> 
> ### NodeJS Version
> NodeJS: 14.18.1
> 
> ### MagicMirror Version
> MM: 2.17.1
> 
> ### Remote Control Version
> Remote Control: 2.3.6
> 
> ### Did you try using just Remote Control alone with MM?
> * [x]  I have and the error still happening
> 
> ### Description
> I get the following pop-up message in the web browser when executing "Restart MagicMirror", but the function executes and MM restarts.
> 
> ![image](https://user-images.githubusercontent.com/28989417/142620485-f0142835-9ec2-45bc-98ae-ac62319f8d59.png)
> 
> ### Expected behavior
> I would think a success message or some sort of confirmation that the command was successful.
> 
> ### Current behavior
> Error message pop-up.
> 
> ### Possible solution
> _No response_
> 
> ### Steps to reproduce
> 1. Start MM
> 2. Wait until everything loads
> 3. Click "Restart MagicMirror"
> 4. Get error message pop-up after a few seconds.
> 
> ### Log
> ```shell
> N/A
> ```
> 
> ### config.js
> ```js
> /* Magic Mirror Config Sample
> *
>  * By Michael Teeuw https://michaelteeuw.nl
>  * MIT Licensed.
>  *
>  * For more information on how you can configure this file
>  * see https://docs.magicmirror.builders/getting-started/configuration.html#general
>  * and https://docs.magicmirror.builders/modules/configuration.html
>  */
> let config = {
> 	address: "0.0.0.0", 	// Address to listen on, can be:
> 							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
> 							// - another specific IPv4/6 to listen on a specific interface
> 							// - "0.0.0.0", "::" to listen on any interface
> 							// Default, when address config is left out or empty, is "localhost"
> 	electronOptions: {
> 		webPreferences: {
> 		webviewTag: true
> 		}
> 	},
> 	port: 8080,
> 	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
> 					// you must set the sub path here. basePath must end with a /
> 	ipWhitelist: ['127.0.0.1','localhost','192.168.200.0/24'], 	// Set [] to allow all IP addresses
> 															// or add a specific IPv4 of 192.168.1.5 :
> 															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
> 															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
> 															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
> 
> 	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
> 	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
> 	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true
> 
> 	language: "en",
> 	locale: "en-US",
> 	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
> 	timeFormat: 24,
> 	units: "imperial",
> 	// serverOnly:  true/false/"local" ,
> 	// local for armv6l processors, default
> 	//   starts serveronly and then starts chrome browser
> 	// false, default for all NON-armv6l devices
> 	// true, force serveronly mode, because you want to.. no UI on this device
> 
> 	modules: [
> 		{
> 			module: 'MMM-Remote-Control',
> 			// uncomment the following line to show the URL of the remote control on the mirror
> 			// position: 'bottom_left',
> 			// you can hide this module afterwards from the remote control itself
> 			config: {
> 				customCommand: {},  // Optional, See "Using Custom Commands" below
> 				showModuleApiMenu: true, // Optional, Enable the Module Controls menu
> 				secureEndpoints: true, // Optional, See API/README.md
> 				// uncomment any of the lines below if you're gonna use it
> 				// customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
> 				apiKey: "********************", // Optional, See API/README.md for details
> 				// classes: {} // Optional, See "Custom Classes" below
> 			}
> 		},
> 	]
> };
> 
> /*************** DO NOT EDIT THE LINE BELOW ***************/
> if (typeof module !== "undefined") {module.exports = config;}
> ```
> 
> ### Additional info
> _No response_

I had a similar problem.
i used @sdteweils script for installing MM. He named the process "MagicMirror". MMM-remote-control uses "mm".

I just chaged the node_helper.js in line 959 to "MagicMirror". At the moment everything works. Cross fingers.

**Comment by ezeholz** [comment]
How did you installed the MM @Coolie1101 ?
Did you try reinstalling?

Actually @OberfragGER , you can add an option to your config file, I believe it's `processName`. That way you can modify the default name of `mm` without modifying node_helper.

**Comment by Coolie1101** [comment]
I installed via the Manual Installation instructions at https://docs.magicmirror.builders/getting-started/installation.html#manual-installation, MMM-Remote should be able to or is finding "MM", as mentioned in the original post MM does restart, "pm2 restart mm" works as well.

**Comment by OberfragGER** [comment]
> How did you installed the MM @Coolie1101 ? Did you try reinstalling?
> 
> Actually @OberfragGER , you can add an option to your config file, I believe it's `processName`. That way you can modify the default name of `mm` without modifying node_helper.

Thanks a lot. Found i now with the help of you and also after that google.
Its corecctly 'pm2ProcessName'

Google found the right hint from you @ezeholz ! Thank you!
