### ISSUE TITLE
Request modules on/off function according to the schedule.

### ISSUE THREAD

**Issue by starsirius9** [Jopyth/MMM-Remote-Control#273]
### Description

The remote control function is too convenient to set up the magic mirror from outside. If there is a schedule function, it would be much more convenient to control the module or the monitor at the desired time. If you are considering an upgrade in the future, please add a scheduling function.

**Comment by ezeholz** [comment]
I didn't see this issue since now, I'm so sorry.

Sure! I'll have it in mind. I'm pretty sure that some other module must have this functionality, but we could add this on RC aswell.
Thanks!
