### ISSUE TITLE
German term "Ausschalten" confusing

### ISSUE THREAD

**Issue by SaschaMorgenstern** [Jopyth/MMM-Remote-Control#28]
Hello.  
First of all, props to you for this Module. Great work.

Everytime I use the remote I am confused about the term "Ausschalten".
Maybe it's better to use "Energieoptionen", cause "Ausschalten" means the final and normally last executable action. But the "button" is refering to more actions which are useful for energy saving options.

edit: wanted to label the "issue" as enhancement, but can't find the option for labeling

**Comment by Jopyth** [comment]
I agree "Ausschalten" is not perfect. I think in a previous version I had "An-/Ausschalten" or something like that.

**Comment by Jopyth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [German translation issue](https://trello.com/c/pqOKatcs/27-german-translation-issue)

**Comment by ezeholz** [comment]
I'm gonna need help in this issue, because I don't know anything about German. Feel free to modify [this file](https://github.com/Jopyth/MMM-Remote-Control/blob/master/translations/de.json) in your own fork, and make a PR changing it. I'll be glad to merge it. :D

**Comment by ezeholz** [comment]
Actually, this is already changed. Perfect! Closing this issue
