### ISSUE TITLE
Wifi implementation - Enchancement

### ISSUE THREAD

**Issue by Jt4112** [Jopyth/MMM-Remote-Control#29]
Would it be easy to implement a WiFi option to your module? I want to give a Magic Mirror as gifts (to non-technical people) and use your Module as the setup application. I want them to be able to enter all of their info for the modules like WiFi, email, calendar, Location Data (Weather/Forecast) NFL/NHL teams, etc. However, I'm gonna start with WiFi, because if I don't get the rest implemented I could remote in and setup the rest (when the Mirror is connected to WiFi).

According to the Raspberry Pi Forums:
[https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md](url)

It really only takes a simple "sudo echo" to really setup a new network.

**Comment by Jt4112** [comment]
I now realize that in order to set up the wifi, your module would have to be switched to Bluetooth. Can't setup the WiFi, until you first connect to the mirror with WiFi... I'm not sure how much Bluetooth work would need to be setup to implement this. However the Pi3's and the new Pi-Zero W's come with WiFi and BT pre-installed.

**Comment by lsaguiar** [comment]
Hi @Jt4112 and @Jopyth , I just get now this post, and I would like to have the same solution of @Jt4112 based on bluetooth for first setup. @Jopyth is possible to have this solution? 
Looking forward your reply.

**Comment by Jopyth** [comment]
The WiFi setup would be possible, but as you already described, it would not be possible without a network connection. I don't know how this can be done with Bluetooth.

**Comment by ezeholz** [comment]
I've reviewed this for a long time, and I'm sorry to disappoint those who were expecting this feature, but I don't believe that this module should do it. It's a good idea for a new module that installs everything and configure everything for the first time, but there are a lot of simple installations of the MM. I confident than the UI could change in the future for those who aren't technical people, and that's where I'm aiming for. Hope you guys understand, and if you have any other awesome feature, we can check it out together. Happy 2021 guys! Keep Programming :D
