### ISSUE TITLE
module broken with magicmirror v2.25.0

### ISSUE THREAD

**Issue by khassel** [Jopyth/MMM-Remote-Control#293]
### OS

irrelevant

### NodeJS Version

18 or 20

### MagicMirror Version

2.25.0

### Remote Control Version

latest

### Did you try using just Remote Control alone with MM?

- [X] I have and the error still happening

### Description

[03.10.2023 21:02.54.966] [ERROR] Error when starting node_helper for module MMM-Remote-Control:
[03.10.2023 21:02.54.969] [ERROR] Error: Cannot find module 'node-fetch'
Require stack:
- /opt/magic_mirror/modules/MMM-Remote-Control/scripts/download_modules.js
- /opt/magic_mirror/modules/MMM-Remote-Control/node_helper.js

### Expected behavior

`node-fetch` is installed in the module `package.json`

### Current behavior

`node-fetch` is not installed in the module `package.json` and was removed from mm core.

### Possible solution

install `node-fetch` v2 in the module `package.json`

### Steps to reproduce

Start MM v2.25.0 with module

### Log

```shell
see description
```

### config.js

```javascript
standard
```

**Comment by ezeholz** [comment]
Hello! Cool, I'm gonna change it asap. Thanks!

**Comment by ezeholz** [comment]
Fixed in release 2.3.8!
