### ISSUE TITLE
Modules locked by who/what...

### ISSUE THREAD

**Issue by Snille** [Jopyth/MMM-Remote-Control#32]
Hi! Use your module daily! It's great, thank you!! :)
I have an enhancement suggestion. It would be great to be able to see what modules has currently locked other modules (by for example "hovering" over the locked module or in the "unlock" dialog if the hovering is to much). If I want to "show" a locked module, I get a warning about that it's locked but not by whom/what. When developing new modules it would be good to know for debugging purposes at least. :)

**Comment by Jopyth** [comment]
Good idea!
