### ISSUE TITLE
Classes with activities? 

### ISSUE THREAD

**Issue by MrPineMan** [Jopyth/MMM-Remote-Control#34]
First of all, the website you made is great! And.. this is not an issue but **a request**.

Is it possible to upgrade and tweak the website a littlebit that you have different "classes" for different events. 

I've seen someone created a option in the main menu called "[party mode](https://forum.magicmirror.builders/topic/1000/not-really-a-mirror-at-all-but-is-really-helpful)" which let dissapear all the personal modules and only shows the music player module. 

It should be nice if i could make a party mode, dinner mode, or maybe a daddy, mother etc.. etc.. mode. I'm not interested in the calendar and traffic from my brother or mother. And ofcourse i can activate them all one by one, but is hard because the name duplicates or not user friendly. Another profit about classes is that the CPU usage is way lower than the facial recognition which already used the idea. (my parents are useless when it comes to technology :) )

I see forward to your reply!

**Comment by PH1TCH** [comment]
Hi everyone, 

Custom Classes work great for me, thank you for the implementation. 

My question is: Can they be triggered as an URL request through the API (yet)? 😉

Thanks in advance!

**Comment by ezeholz** [comment]
@PH1TCH Hey! Totally, I'll let you the [online documentation](https://ezeholz.com.ar/MMM-Remote-Control/#/Module%20Control/get_api_classes___value_) but remember that you could check and test this and every other API url using http://ip-of-your-mirror/api/docs
Cheers!

**Comment by PH1TCH** [comment]
@ezeholz That is just great! It totally missed that one. I just tried it and it works flawlessly. I will use it in conjunction with Apple's Shortcuts App und NFC tags. So basically hidden buttons to control the mirror 😉

Thanks again!
