### ISSUE TITLE
Turning off monitor fails without an error

### ISSUE THREAD

**Issue by BerndKohl** [Jopyth/MMM-Remote-Control#38]
Hi,
I am running MM2 with modules MMM-Remote-Control and MMM-ModuleScheduler.

My problem is that turning off the monitor simply doesn't work. I see the HDMI message in the MM-log but the screen simply stays on. It doesn't matter if I try to turn it off by using a schedule in MMM-ModuleScheduler or the web-interfac http://raspi-IP:port/remote.html.

Any ideas where to look?

Kind regards,

Bernd

**Comment by BerndKohl** [comment]
As far as I can see (which is honestly not very far) this modules uses a "tool" called tvservice.
Does this tool come with the module, is it part of raspbian or does it have to be installed before manually?
Searching the web I came across https://pi-buch.info/tag/tvservice/ which states that tvservice might not be the best way of turning the monitor off and on but vcgencmd.
Can this be used/integrated/delivered as substitute for tvservice?

**Comment by BerndKohl** [comment]
Using vcgencmd as suggested above did not solve my problem. I had to use a different approach:
I wrote two shell scripts and called them instead of tvservice.
Here's what I did:

1. Created script turnoffscreen.sh consisting of:
```
#!/bin/sh
# turn off display
xset -display :0.0 dpms force off
# turn on power management
xset -display :0.0 dpms
```
2. Created script turnonscreen.sh
```
#!/bin/sh
# turn on display
xset -display :0.0 dpms force on
# turn off power management
xset -display :0.0 -dpms
# turn off screensaver
xset -display :0.0 s off
xset -display :0.0 s noblank
```
3. changed <MM_HOMEDIR>/modules/MMM-Remote-Control/node_helper.js like this
```
if (query.action === "MONITORON")
		{
			//exec("tvservice --preferred && sudo chvt 6 && sudo chvt 7", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
			exec("/usr/local/bin/turnonscreen.sh && sudo chvt 6 && sudo chvt 7", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
			return true;
		} 
		if (query.action === "MONITOROFF")
		{
			//exec("tvservice -o", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
			exec("/usr/local/bin/turnoffscreen.sh", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
			return true;
		} 
```
Et voilá: it worked.

Maybe someone can integrate this?

There is most probably room for improvement (e.g. use only one script and pass parameter on/off to it, ...), so please feel free to do so.

**Comment by Jopyth** [comment]
The monitor on and off function is the one most dependent on system and OS. I do not think there is a single solution which works for everyone here. I have read a little bit about the topic, but I do not remember why the final choice was the `tvservice` solution. Can you provide a source for your solution? Does it work on all or at least as many configurations as the `tvservice` command?

**Comment by BerndKohl** [comment]
I used this on a different project and done a lot og googling. Currently I only can speak for Raspbian Jessie.
Tvservice did not work for Raspbian, so I tried "my" googled solution...

**Comment by danjys** [comment]
Change the command to:
vcgencmd display_power 0 (For off)
vcgencmd display_power 1 (For on)

This is keep the screen buffer state alive. While tv service forgets the screen buffer state hence MONITORON appears to fail 

Issue with using tvservice: (From Raspberry Pi Documentation)

Important Note: Powering off the output using this command will also destroy any framebuffers/dispmanx layers associated with the display. These are NOT re-established with a subsequent power on, so will result in a blank screen.

A better option is to use the vcgencmd display_power option, as this will retain any framebuffers, so when the power is turned back on the display will be the returned to the previous power on state.
