### ISSUE TITLE
Support for notifications from other modules

### ISSUE THREAD

**Issue by ianperrin** [Jopyth/MMM-Remote-Control#4]
Does the module support notifications from other modules to trigger the actions. For example could I call `sendNotification("MONITOROFF")` from my module and have your module perform the work?

**Comment by Jopyth** [comment]
I think this would be possible, yes. I will look at the PR.

**Comment by Jopyth** [comment]
I think the basic idea is great, I would implement it a little bit differently (see review of #5).

**Comment by ianperrin** [comment]
I've refactored the implementation to take on board your comments. How does it (#5) look now?

**Comment by Jopyth** [comment]
Thank you, looks good.

**Comment by Jopyth** [comment]
Found one more thing, which might be a bug, see #5 again. If you have tested it, and it works, I will merge it.
