### ISSUE TITLE
curl http requests not working

### ISSUE THREAD

**Issue by Isokya** [Jopyth/MMM-Remote-Control#42]
Sorry if this is a really newbie question but when I try to do `curl http://localhost:8080/remote?action=NOTIFICATION&notification=SHOW_ALERT&payload={%22title%22:%22Alert%22,%22message%22:%22This%20is%an%20alert.%22}` through Terminal, it says it was successful but nothing happens on my mirror. Entering the URL through Chrome works.

**Comment by Jopyth** [comment]
Have you figured it out? I guess you need to escape spaces in a different way when using curl?

**Comment by BerndKohl** [comment]
You could try  
`curl -G --data-urlencode "action=NOTIFICATION" --data-urlencode "notification=SHOW_ALERT" --data-urlencode "{title: Alert, message: This is an alert.}" http://localhost:8080/remote`
