### ISSUE TITLE
Icons in Webinterface missing since update on MM Version v2.1.1

### ISSUE THREAD

**Issue by khassel** [Jopyth/MMM-Remote-Control#44]
Hi, 

after updating the MagicMirror repo the webinterface http://192.168.1.13:8080/remote.html#main-menu looks like this:
![grafik](https://cloud.githubusercontent.com/assets/25914086/24582423/f680c7d2-172f-11e7-9c1e-dd8aa3b985b8.png)

All Icons are missing ...

Karsten.

**Comment by Jopyth** [comment]
Thank you, I know this is an issue, should be already fixed on the develop branch. I hope I can make a release today to fix it.

**Comment by izanbard** [comment]
Would love to see this fix published

**Comment by Jopyth** [comment]
Sorry, I am currently not at home, but will merge this on the weekend. Or can someone confirm that the develop branch works fine on the new version as is? Then I might be able to do it from my phone.

**Comment by Jopyth** [comment]
Should be finally fixed now in 1.1.3.
