### ISSUE TITLE
Monitor On function does not work 

### ISSUE THREAD

**Issue by d31r** [Jopyth/MMM-Remote-Control#45]
Hi, 

Great module btw, that's what I was looking for.

Everything works fine, except when I turn off the monitor and want to turn it back on.

When turned off, the screen goes into power saving mode -> OK
When turned on, it displays a single flashing line, like it was waiting for me to type ...

I tried refreshing the browser, that does not help
Only restarting the RPI gets the MM working again

help please!!

**Comment by Jopyth** [comment]
I do not know how to fix this. You basically need the correct console commands, maybe you can figured out which ones work for you?

The module is using these (but different ones can found online):
`tvservice --preferred && sudo chvt 6 && sudo chvt 7`
`tvservice -o`

**Comment by kyle-kelly** [comment]
I ran into this same problem. Adding ```sudo``` in front of the commands resolved my issue. another option would be to use ```vcgencmd display_power 0``` and ```vcgencmd display_power 1```.

**Comment by felixgonschorek** [comment]
Same problem here, monitor switches through several connectors (HDMI, VGA, DVI) and Raspberry does not recognize the monitor in this state.

vcgencmd display_power 0/1 works for me too, trying to find where to patch MMM-Remote-Control.

**Comment by felixgonschorek** [comment]
changing these two lines fixed it for me:
```
diff --git a/node_helper.js b/node_helper.js
index d0e509a..e24fff8 100644
--- a/node_helper.js
+++ b/node_helper.js
@@ -595,12 +595,12 @@ module.exports = NodeHelper.create({
                }
                if (query.action === "MONITORON")
                {
-                       exec("tvservice --preferred && sudo chvt 6 && sudo chvt 7", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
+                       exec("vcgencmd display_power 1", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
                        return true;
                }
                if (query.action === "MONITOROFF")
                {
-                       exec("tvservice -o", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
+                       exec("vcgencmd display_power 0", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });
                        return true;
                }
                if (query.action === "HIDE" || query.action === "SHOW")
```

**Comment by felixgonschorek** [comment]
more info on several options to turn on/off the monitor with explanation of benefits/drawbacks:

https://www.screenly.io/blog/2017/07/02/how-to-automatically-turn-off-and-on-your-monitor-from-your-raspberry-pi/
