### ISSUE TITLE
Not allowed to access...

### ISSUE THREAD

**Issue by Rattenjunge8080** [Jopyth/MMM-Remote-Control#47]
Hi,

so i added the IP address in the config.js from my phone, like the manual says.
But the access is denied, even the console (where I start the Magic Mirror) is saying: Access denied to IP address: 192.168.188.45

Here is my IP-Whitelist: 

 ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.188.45"],

Is there an easy way to avoid this Whitelist stuff? I really don't need it.

Thanks!

**Comment by Rattenjunge8080** [comment]
Alright, I`m a retard. Just make the whitelist like this:

ipWhitelist: [],

and every IP has access. Sorry

**Comment by SanSahInnovations** [comment]
@Rattenjung8080 I tried the same way my mirror is not booting now
It just display nothing and I can't even acess it remotely
