### ISSUE TITLE
Change function of turn on/off monitor

### ISSUE THREAD

**Issue by hadadux** [Jopyth/MMM-Remote-Control#48]
hey, maybe u can help me to change the function (turn on/off the monitor => disable hdmi screen) to dim the brightness and set the min (10?) and max (200?) value. 

This avoids the problem of not finding a signal of the monitor.

**Comment by Jopyth** [comment]
You could instead hide all modules maybe? E.g. use the code of the hide all button (https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.js#L1386-L1391) and move it to the `monitor-off-button` https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.js#L1443. Or send the appropriate notifications from a PIR module if you have that?

**Comment by ezeholz** [comment]
@hadadux So I recently was experimenting with that, so I think that [this](https://vitux.com/control-screen-brightness-from-ubuntu-terminal/) link might help.
After that, you could use [Custom Commands](https://github.com/Jopyth/MMM-Remote-Control#using-custom-commands) to set your brightness at the amount you want.
