### ISSUE TITLE
Including position in config.js does not allow mirror to boot

### ISSUE THREAD

**Issue by SirtajS** [Jopyth/MMM-Remote-Control#49]
When I commenting the position for the address of the remote, the config.js file cannot be found when starting the mirror. By removing that line or making the position a comment again, everything is fine and the remote works.

**Comment by Jopyth** [comment]
Please check that the comma is still there. It sounds like you removed it by accident. This will not work:
```
{
    module: 'MMM-Remote-Control'
    // uncomment the following line to show the URL of the remote control on the mirror
    position: 'bottom_left'
    // you can hide this module afterwards from the remote control itself
},
```
Instead you need a comma:
```
{
    module: 'MMM-Remote-Control'
    // uncomment the following line to show the URL of the remote control on the mirror
    , position: 'bottom_left'
    // you can hide this module afterwards from the remote control itself
},
```
