### ISSUE TITLE
Module updates not noticed without restart

### ISSUE THREAD

**Issue by qistoph** [Jopyth/MMM-Remote-Control#52]
The status of modules is loaded on initialization of the MMM-Remote-Control module. When an update of a module is available this is only noticed after restarting (and reinitializing) the MMM-Remote-Control module.

**Comment by finostrozac** [comment]
How do i restart?

**Comment by ezeholz** [comment]
I'm gonna work into this in the future. I'm gonna markdown [this line](https://github.com/Jopyth/MMM-Remote-Control/blob/2daec303f5ddea8288daedfa2941dc9e9bba4d8b/node_helper.js#L60), so I can come back later. Probably we'll need to set an interval just like calendar or news module.
