### ISSUE TITLE
Asks for User and Password

### ISSUE THREAD

**Issue by finostrozac** [Jopyth/MMM-Remote-Control#53]
I've installed the repository and added it to the config.js and my ip the the ipWhiteList. I have no error, but when i put my IP on the web browser it asks for a Username and Paddword. Any idea? don't know what else to do, Thanks

**Comment by edward-shen** [comment]
As far as I know this module should not require, nor request, a user/pass combo. Can you provide a screenshot/video, your config.js, and your MagicMirror IP address?

**Comment by finostrozac** [comment]
![20170830_190056](https://user-images.githubusercontent.com/31463429/29897262-7e36e4c0-8db6-11e7-84b3-1ce38aaed9d4.jpg)
![20170830_185953](https://user-images.githubusercontent.com/31463429/29897263-7e3d948c-8db6-11e7-9f08-3b1cae3af693.jpg)

Now am getting this. Any idea? Thanks
![rc](https://user-images.githubusercontent.com/31463429/29897302-b23907d0-8db6-11e7-9333-9acc7d20ce0b.png)

**Comment by israel05** [comment]
Delete your previous post ASAP! That os your wan ip, not your lan  ip

**Comment by edward-shen** [comment]
Go to your raspberry pi, and open up a terminal. Type `ifconfig` and look for an ip address that is in the range of 192.168.1.0 to 192.168.1.255. That is your Magic Mirror's LAN IP Address. Save it, you'll need it for later.

Next, go to your computer, and type in `ipconfig`. Again, look for an IP address from 192.168.1.0 to 192.168.1.255. That is your computer's LAN IP address.

You want to whitelist your computer's LAN IP address, not your public IP address.

Then, you can access your Magic Mirror by going to your Magic Mirror's LAN IP Address.

If you want to access the remote admin page, you'll need to add `:8080/remote.html` to the end of your MagicMirror's LAN IP address.

**Comment by finostrozac** [comment]
got it working!!. Thanks to both. Love you hahaha

**Comment by edward-shen** [comment]
Please don't forget to close this issue!
