### ISSUE TITLE
This device is not allowed to access your mirror.  Please check your config.js or config.js.sample to change this.

### ISSUE THREAD

**Issue by goprojojo** [Jopyth/MMM-Remote-Control#55]
I allowed all IP addresses with [], but after restart (pm2 restart mm) it shows a black screen. When I go to the url http://192.168.x.x:8080/remote.html it returns: "This device is not allowed to access your mirror.  Please check your config.js or config.js.sample to change this." 

> var config = {
>         port: 8080,
>         ipWhitelist: [],                                  // Set [] to allow all IP addresses
>                                                                // or add a specific IPv4 of 192.168.1.5 :
>                                                                // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
>                                                                // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
>                                                                // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

**Comment by Jopyth** [comment]
I think this is a (known) issue in the core project: https://github.com/MichMich/MagicMirror/issues/950

**Comment by weixuan1005** [comment]
Hey jopyth how do I add the ipaddress into the ipwhitelist

**Comment by Jopyth** [comment]
You need to change your `config.js`. Does this help: https://forum.magicmirror.builders/topic/1326/ipwhitelist-howto ?

**Comment by weixuan1005** [comment]
It still cannot work

**Comment by Jopyth** [comment]
Check this issue, and my last comment: https://github.com/Jopyth/MMM-Remote-Control/issues/56

**Comment by BLoodConstructions** [comment]
After those 

var config = {
port: 8080,

I ve inserted 
address: „0.0.0.0“,

And than everything works fine again.

**Comment by weixuan1005** [comment]
Comment #56 from which website?

**Comment by thammanitn** [comment]
getDom: function() {
        var wrapper = document.createElement("div");
        if (this.addresses.length === 0) {
            this.addresses = ["ip-of-your-mirror"];
        }
        wrapper.innerHTML = "http://" + this.addresses[0] + ":8080/remote.html";
        wrapper.className = "normal xsmall";
        return wrapper;
    },

**Comment by Chello** [comment]
I have a similar problem. When I try to connect to the web page it appears the error (in title).
My config: 
`address: "0.0.0.0", 
port: 80,
ipWhiteList:["192.168.1.3"],
`
When I try to open the page the terminal response is:
`Access denied to IP address: 192.168.1.3`

I have installed it in a Docker Container (it seems that port forwarding is working because I can read the error message on the browser). I really cannot figure out the problem
