### ISSUE TITLE
Can't connect to the server....

### ISSUE THREAD

**Issue by Reotch2** [Jopyth/MMM-Remote-Control#56]
I'm unable to connect even after []'ing the whitelist.  This is likely an isolated issue, since I'm running a strange mix.

Hardware: RPI3
OS: Raspbian Stretch
Electron: 1.4.15
MM: 2.1.3

On a previous setup I didn't have any issues.  This time I opt'd to install Stretch instead of LXDE, and I'm running Electron 1.4.15 to save CPU usage (works wonderfully).  

Unfortunately, no matter how I configure the whitelist, it seems like the remote server isn't running... at all.  

any thoughts? 

Thanks,
Rich

**Comment by Jopyth** [comment]
Do you get `This device is not allowed to access your mirror. Please check your config.js or config.js.sample to change this.` or something else?

**Comment by Reotch2** [comment]
First and foremost.. I'm new-ish to linux and JS, so this is more than likely a "me" problem.  

Unfortunately, I don't think this is a whitelist issue.    I don't think that they are related.  I used the most recent Stretch Image.  Uninstalled electron 1.7.#, reinstalled electron 1.4.15.  Reinstalled all my baseline modules (underground, news, simple logo, newsfeed, etc).. and most importantly.. Remote Control using the auto-install script.  

What's odd, is it seems that the web server isn't even running.  Electron boots on-screen without any issues, but I can't access the MM page remotely using http://192.168.#.##:8080.  I keep getting a "can't connect to server..."  

I guess.. the underlying issue is that I can't access the MM page remotely at all.  Thoughts?

Any help would be appreciated.

**Comment by Reotch2** [comment]
Yup.....This may be the issue.

https://forum.magicmirror.builders/topic/5025/can-t-access-magic-mirror-via-http

**Comment by Jopyth** [comment]
For others searching: [solution and explanation in the forum](https://forum.magicmirror.builders/post/28777)
