### ISSUE TITLE
Unsuspected token

### ISSUE THREAD

**Issue by G0vernment** [Jopyth/MMM-Remote-Control#61]
Its just this single line of code that makes the entire MM not start and just end up with the: you havnt configured your config.js thingy.
{
module: "MMM-Remote-Control"
position: "bottom_left"       <----- This line crashes the startup
},

**Comment by slametps** [comment]
@G0vernment there is a missing comma after MMM-RemoteControl.

**Comment by G0vernment** [comment]
You are completely right, thats my bad 👍
