### ISSUE TITLE
Add one more menu "Show video files" in the remote.html

### ISSUE THREAD

**Issue by dexterbeng** [Jopyth/MMM-Remote-Control#62]
In the remote site, if I want to add one menu is to read a directory and list video files from the directory, how do I implement in the MMM.Remote-Control.js & remote.html?

![capture](https://user-images.githubusercontent.com/29851477/34647839-1df0dec6-f3c9-11e7-9116-e01c715dc86e.PNG)
after clicking that "Show video files", it will show a list of the video files from the directory path and able to play it.
![path](https://user-images.githubusercontent.com/29851477/34647842-1fda0b2c-f3c9-11e7-91e4-2c480ba636ca.PNG)
This is the directory path.

**Comment by Jopyth** [comment]
Copied from my forum message:

> Have a look at these lines, this is a simple button: https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.html#L134-L137 You will need a new one for your own idea. Also you since you want to load a list of files, you might want to look at the edit menu: https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.html#L49-L73
> Then you will also need to implement the logic for list loading, e.g. for the edit menu you can see this here: https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.js#L543-L572
> And also to activate the general menu you need something similar to this ( https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.js#L219-L222 ) for your menu.
> Finally you need to send a notification to the mirror, and then listen to it in a module, to start activating the video.
> This in the case of the edit list is implemented in https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.js#L505-L541
> In this method at the bottom, you can see that the showModule and hideModule methods are called https://github.com/Jopyth/MMM-Remote-Control/blob/master/remote.js#L325-L331
> 
> Hope this helps to get you started.

**Comment by joelman** [comment]
Have you considered a more modular way of customizing the module?  One that wouldn't involve directly editing the remote.html and remote.js files?  Like maybe it could (somehow) pull in html javascript methods defined by another module?
