### ISSUE TITLE
GET request to trigger a RaspberryPi restart doesn't work

### ISSUE THREAD

**Issue by Ehsan-Shams-Davodly** [Jopyth/MMM-Remote-Control#66]
When i run http://192.168.xxx.xxx:8080/remote?action=RESTART, it does not restart and it shows this error {"status";"error","reason";"unknown","info";null}. how can i solve this problem?

**Comment by ezeholz** [comment]
It's all about the new API module. You should use `/api/reboot` in order for it to work. Cheers :D
