### ISSUE TITLE
MM2 restart button doesn't seem to do anything

### ISSUE THREAD

**Issue by StrawberryYoghurt** [Jopyth/MMM-Remote-Control#7]
Rebooting the Rpi, turning the screen on and off both work fine, but the restart MM2 button doesn't do anything, seemingly. 

What could be the problem?

**Comment by Jopyth** [comment]
It currently only works if you set up auto starting as described [here](https://github.com/MichMich/MagicMirror/wiki/Auto-Starting-MagicMirror). 

How do you start your your program?

**Comment by Jopyth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compatibility of Restart Command](https://trello.com/c/jCwQT9lN/8-compatibility-of-restart-command)
