### ISSUE TITLE
Unable to access the remote interface

### ISSUE THREAD

**Issue by andrew16x** [Jopyth/MMM-Remote-Control#74]
Hello,

I have installed the module as per the instructions listed in the documentation, however I seem to be unable to access the remote interface via http://192.168.x.x:8080/remote.html - i receive 

>This site can’t be reached
192.168.x.x refused to connect.

I must admit I wasn't quite sure what IP addresses I need to add in the `ipWhiteList`, would this be something like any device from my network, i.e. my PC?

Anyway I saw that you can set `ipWhiteList` to allow all devices with `[]`, tried that but did not make a difference.

Any help would be appreciated?

Regards,

Andrew

**Comment by budddesilva** [comment]
I have the exact same issue mate. I hope we find an answer.

**Comment by Jopyth** [comment]
See #73 .
