### ISSUE TITLE
Pi refuses connection

### ISSUE THREAD

**Issue by VH-Tech** [Jopyth/MMM-Remote-Control#75]
hi, 
I downloaded and executed your module as per the directions in Readme.Md
but when I try to connect to my pi using the browser it's unable to connect to my pi,
and I have added my pc's Ip address to the IP whitelist as well
image 1:
![complaint1](https://user-images.githubusercontent.com/37875901/39481354-c266f594-4d88-11e8-9639-404ec3855465.PNG)

image 2:
![complaint](https://user-images.githubusercontent.com/37875901/39481363-caca6cfc-4d88-11e8-8187-753ad2ee4496.PNG)

my IP whitelist : 
ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.4.5/24"]
in which my pcs ip address is 192.168.4.5/24

**Comment by VH-Tech** [comment]
Thanks a lot!!
It worked for me as well!!

**Comment by dmwilsonkc** [comment]
In config.js:

Replace: address: "localhost", With: address: "0.0.0.0", and
Replace: ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], with ipWhitelist: ["127.0.0.1", "192.168.X.1/24"],

Is what worked for me, and it does not whitelist anything but what is on my local network. Changing it to [] leaves it open for any ip to connect.
