### ISSUE TITLE
Brightness does not work when triggered by notifications (With resolution)

### ISSUE THREAD

**Issue by glitch452** [Jopyth/MMM-Remote-Control#76]
Goto: node_helper.js --> executeQuery function --> if (query.action === "BRIGHTNESS")...

The line "res.send({"status": "success"});" causes an error when calling the function with a notification because the variable res is null... Replace the line with "if (res) { res.send({"status": "success"}); }" to resolve the issue.

**Comment by ezeholz** [comment]
Hey! This issue seems to be resolved, but if not feel free to reopen it. Cheers! :D
