### ISSUE TITLE
Help setting title/message in SHOW_ALERT

### ISSUE THREAD

**Issue by ttanman23** [Jopyth/MMM-Remote-Control#79]
Hello,
I am trying to remotely send an alert to the mirror but I don't know the correct format to set my own title and message. 
Entering the following shows a default title of "Note" and default message of "Attention":
 **/usr/bin/curl -X GET http://{mmipaddress}:{mmPort}/remote?action=SHOW_ALERT**

How would I change the title and message? Something like...?
 /usr/bin/curl -X GET http://{mmipaddress}:{mmPort}/remote?action=SHOW_ALERT&title='My Alert'&message='This is my message'

**Comment by labomat** [comment]
http://{ip}:{port}/remote?action=SHOW_ALERT&title=This%20is%20my%20title%21

**Comment by ttanman23** [comment]
Thank you. I had problem with quotes. Needed them in front of http and behind the last character

/usr/bin/curl -X GET **"**http://{mmipaddress}:{mmPort}/remote?action=SHOW_ALERT&title=My%20Alert**"**
