### ISSUE TITLE
Need help about voice control sendnotification

### ISSUE THREAD

**Issue by stantang986** [Jopyth/MMM-Remote-Control#8]
Hi,
I tried to use [Module: Voice Control](https://github.com/alexyak/voicecontrol) to sendNotification to Remote Control, but no lucky.

The setting of Voice Control in config.js:
`{
            module: 'voicecontrol',
            config: {
                models: [
                    {
                        keyword: "ycsy",   // keyword
                        description: "Say 'ycsy' to hide clock",
                        file: "ycsy.pmdl", // trained model file name
                        message: "HIDECLOCK"   // notification message that's broadcast in the MagicMirror app
                    }
                ]
            }
        },`

For Remote Control here, i really have no idea:
`{
    module: 'MMM-Remote-Control',
    notificationReceived: function(notification, payload, sender) {
        if (notification === "HIDECLOCK"){
            **WHAT SHOULD I PUT HERE, have tried many times, all failed**
        }
},`

**Comment by Jopyth** [comment]
I am sorry, but what you want to do, doesn't work right now. I will see when I have the time to add this and how this can be done.

**Comment by stantang986** [comment]
Ah...I'm thinking that hide/show action not only access the web page, especially stand in the front of mirror, looking clearly how many acnes on my face...  ^_-

**Comment by Jopyth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compatibility to Voice Control](https://trello.com/c/7gQPqh7o/7-compatibility-to-voice-control)

**Comment by Jopyth** [comment]
I think this would be best changed in the voice control module to support remote notifications.
