### ISSUE TITLE
Using remote?action=SHOW_ALERT&type=notification&... does not change the time the message is shown (always 4sec)

### ISSUE THREAD

**Issue by BluP62** [Jopyth/MMM-Remote-Control#80]
Hi Jopyth,
thank a lot for this great module. I'm using it also to show/hide an iframe from a Raps acting as a Webcam with Motion.
Playing with the alert/notification functions I realised, that there is a different behaviour of the timer when using the remote action show_alert type=alert/notification.

Using the remote?action request with the notification type via webbrowser or curl or MagicRemote does not change the time the notification is shown. 
If I use the type alert, the time requested is used.

I checked using Wireshark what is send from MagicRemote and could prove that the correct value is sent.
e.g.
http://MyMMIP:8080/remote?action=SHOW_ALERT&type=notification&title=TestTitle&message=TestMessage&timer=30

Notification is shown but the timer value seems to be ignored. Everything works as expected using type=alert

Thanks, BluP62

**Comment by Jopyth** [comment]
This is correct, the alert module of the main project does not support a time parameter (see [the documentation](https://github.com/MichMich/MagicMirror/tree/master/modules/default/alert#notification-params)).
If you want this functionality, you could file and issue or PR in the main project.
