### ISSUE TITLE
Crashes the mirror

### ISSUE THREAD

**Issue by ireeus** [Jopyth/MMM-Remote-Control#82]
When the app is configured and able to display on a remote PC the mirror shows black screen.

**Comment by Rutul27** [comment]
How did you solve it?

**Comment by irekwojcik** [comment]
Rutul27 as far as I remember the correct installation made it working. I gave up the project anyway.

**Comment by Rutul27** [comment]
Thank you for your response actually, some of your comments helped me solve it and its working for me now @irekwojcik
