### ISSUE TITLE
support for other device.

### ISSUE THREAD

**Issue by eouia** [Jopyth/MMM-Remote-Control#83]
Hi.
Your nice module has shell scripts(eg. screenoff) for RPI are hardcoded. It makes this module to work limitedly on other platform. (on PC or Asus TinkerBoard, ...).
Could you make your hardcoded command configurable? 
For example, you can provide script sets defined as `rpi.js`, `atb.js` (or users could do by copying your default js and modifying it.). And which script set will be used in configuration.
How do you think about it?

**Comment by shbatm** [comment]
Support for custom monitor commands are included in PR#104.  This could be expanded to the other shell scripts.
