### ISSUE TITLE
Installed on config, now MM doesn't show up

### ISSUE THREAD

**Issue by Heronemau5** [Jopyth/MMM-Remote-Control#9]
I followed the instructions and installed in my config file and now my MagicMirror only loads up to the blank black screen sometimes and the no config page other times. I put my script into a java checker and it only has the one error same as with the default script "One undefined variable
83	module"
Attached is a txt version of my config.js
[config.txt](https://github.com/Jopyth/MMM-Remote-Control/files/576713/config.txt)

**Comment by Jopyth** [comment]
I copied this exactly into my config.js, and it works for me. Are you sure you have not changed anything else?

**Comment by Heronemau5** [comment]
I did not. On another instance i minimized and check my terminal and it seems it may be getting hung up somewhere in the MM launch

> magicmirror@2.0.0 start /home/pi/MagicMirror
> electron js/electron.js

Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
No helper found for module: MMM-Remote-Control.
All module helpers loaded.
Starting server op port 8080 ... 
Server started ...
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.

Normally, after it is completely launched, it will show a new line of pi@raspberrypi:~/MagicMirror $. If I close MM and edit the config.js to my other saved .txt without the module lines it launches just fine

**Comment by Jopyth** [comment]
As I said, the config is fine. However the output of your start shows `No helper found for module: MMM-Remote-Control.` which indicates it can not find the module.

Please check that this command `cd /home/pi/MagicMirror/modules/MMM-Remote-Control` leads into the Remote-Control directory.

**Comment by Jopyth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Black screen on correct config.js](https://trello.com/c/9ZgKqZ2r/9-black-screen-on-correct-config-js)

**Comment by Jopyth** [comment]
Closing this for now, feel free to reopen.
