### ISSUE TITLE
Turn monitor on

### ISSUE THREAD

**Issue by adbeem** [Jopyth/MMM-Remote-Control#90]
Hi there i'm a total noob at this! I can turn off the monitor easily on the remote.html power menu but turning back on the monitor never works for me. Even pressing the power button on the monitor doesnt turn on by itself unless i restart raspberry

**Comment by nixmeer** [comment]
Hello,

I got the same issue. Replacing two lines in the script as described [here](https://github.com/Jopyth/MMM-Remote-Control/issues/38#issuecomment-287279889) solved the problem for me. 

At least for a couple of hours. Currently I auto-reboot my Pi every 12 hours since it won't turn back on after a view hours more. Anyone any idea?

Best

**Comment by nixmeer** [comment]
Hi again,

I was wrong yesterday. I used different lines than in the linked post. 

Go to /MagicMirror/modules/MMM-Remote-Control and open node_helper.js. Find if(query.action === "MONITORON") and replace following line beneath:

`exec("tvservice --preferred && sudo chvt 6 && sudo chvt 7", opts, function(error, stdoutdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });`
                        
insert 

`exec("vcgencmd display_power 1", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });`

instead. 

I did the same for the "MONITOROFF" action using 

`exec("vcgencmd display_power 0", opts, function(error, stdout, stderr){ self.checkForExecError(error, stdout, stderr, res); });`
              
Hope that works for you!

**Comment by adbeem** [comment]
thanks nixmeer :D

**Comment by nixmeer** [comment]
adbeem, does it work a couple of days in a row? I can't turn the screen on after approximately 12 h so I auto-reboot every 12 h and turn the screen of in my startMagicMirror script...

**Comment by adbeem** [comment]
hi nixmeer i try the other method which uses fake kms and it works pretty well for me

**Comment by wtrdk** [comment]
> hi nixmeer i try the other method which uses fake kms and it works pretty well for me

Hi @adbeem, what do you mean by 'fake kms'? Thanks!

**Comment by Jopyth** [comment]
You can now change the command yourself via a config, if you update to the newest version: https://github.com/Jopyth/MMM-Remote-Control#using-custom-commands
