### ISSUE TITLE
is it possible to use this to also click buttons on my magic mirror?

### ISSUE THREAD

**Issue by mirror-master** [Jopyth/MMM-Remote-Control#91]
*Not an Issue But a Question*

I was wondering, with the wonderful features of this module, is it possible move from slide to slide in(MMM-Carousel with navigation) using this?  Or to be able to click the mic button on MMM-AssistankMk2?  Im no pro, i can edit and play with code, Ive never been good enough to create it.  I was looking at the notification and alert section of your module.  But again. no clue on how to do so.

**Comment by Jopyth** [comment]
Clicking is not possible but sending a notification could be possible, if the other modules support acting on them.
