### ISSUE TITLE
Can't connect to the remote interface from my phone

### ISSUE THREAD

**Issue by LordFite** [Jopyth/MMM-Remote-Control#92]
Like most people, I am receiving the message "This device is not allowed to access your mirror.  Please check your config.js or config.js.sample to change this"

Here is my code:

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.x.xx"],

Every other issue that I have seen have only given fix actions as adding 0.0.0.0 to the address and adding my phones IP to the whitelist, but I am still not able to get to the interface.

**Comment by LyoMat** [comment]
Same error. Made whitelist open to all interfaces as well, however html page inaccessible.

Created range, ineffective too.

**Comment by adbeem** [comment]
try remove "::ffff:" if you have IPv4. For example mine is below:
address: "0.0.0.0",
port: 8080,
ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "192.168.1.118"]

**Comment by ozl01** [comment]
I got mine to work. My problem was I forgot to whitelist my phone's ip address. If you can do it from your PC's browser then you should be able to do it from your phone's browser. 

I'm barely getting parts together for my mirror but I was testing everything out on my PC. Before I whitelisted my phone's ip address, my phone's browser would display something like "192.168.x.x is not authorized to connect" so I just put that ip address in my whitelist, restarted, and I could connect.

address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "192.168.x.x", "192.168.x.x"],

**Comment by Jopyth** [comment]
Feel free to reopen if the problem is still there, the comments above should be the solution.
