### ISSUE TITLE
Monitor keeps turning back on after 20 minutes after being turned off

### ISSUE THREAD

**Issue by sansari1959** [Jopyth/MMM-Remote-Control#93]
Hi,

Everything works perfect from the local website of the MagicMirror from Safari on my Phone. Really cool that one can control all the features of the MM and more! 

Not sure, however, whether this is a bug or a feature. Each time I turn monitor off, I expect the monitor to remain off until I turn it back on again. However, after about 20 minutes it comes back on again on its own? Is it supposed to work that way? If so, is there a way to force it to remain off until the next time I actually turn it back on manually?

**Comment by ezeholz** [comment]
Hey! So that's not a feature nor a bug from Remote Control. It's from your OS and the way it turn on and off the monitor.
However, I'm gonna close this issue because it's almost two years since last update. Feel free to open a new one if you need more help.
