### ISSUE TITLE
Incorrect address

### ISSUE THREAD

**Issue by Nanny0gg** [Jopyth/MMM-Remote-Control#96]
Hi,

I'm trying to connect my mirror to my phone, but I think the address I have is wrong.
The address my mirror gives me starts 10.2. but all the examples I've seen start with 192.168..

How do I change my mirror so I can use this module?

Thanks in advance

**Comment by Robiv8** [comment]
type in your terminal "ip address"
and look at eth0 or wlan0 what is your ip address? like xxx.xxx.xxx.xxx
this is your ip address of your raspi (dhcp must be on in your router.)
In your config.js at address write this: 0.0.0.0
and
under ipWhitelist write this: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],

on your phone in browser address type this:
your ip ->  xxx.xxx.xxx.xxx
http://xxx.xxx.xxx.xxx:8080/remote.html

**Comment by 3nkidou** [comment]
ps! j'arrive a me connecter sur le Pi avec vpn avec l'adresse ip du Pi

**Comment by 3nkidou** [comment]
bonjour j'ai résolue le problème !
j'ai enlever les ffff des adress ip sur ipwhitelist ex:
ipwhitelist : ["127.0.0.1", "::ffff:127.0.0.1", "::1", "192.168.xxx.xxx", "192.168.xxx.xxx"],
remplacer les xxx par une adresse défini comme le stipule Jopyth

**Comment by Robiv8** [comment]
Please type in english, for all people!

**Comment by Jopyth** [comment]
Please reopen if this is not solved.
