### ISSUE TITLE
Change Pages via Remote Control Interface

### ISSUE THREAD

**Issue by rudibarani** [Jopyth/MMM-Remote-Control#97]
The Module MMM-Page-Selector has become the go-to module for complex layouts. If offers easy to design pages that can be selected via notifications. It would be great to have this integrated into the MMM-Remote-Control frontend, if presence of the module is detected.
https://github.com/Veldrovive/MMM-Page-Selector

**Comment by Robiv8** [comment]
Oh yes! This would be very nice. I have a MM with MMM-Page-Selector and 6 pages. It works like a charm with MMM-Buttons and Physical buttons.

**Comment by Jopyth** [comment]
The branch with these changes is now merged.
